data = {"Irving Abella": "en.wikipedia.org/wiki/Irving_Abella", "Louise Abbott": "en.wikipedia.org/wiki/Louise_Abbott",
        "Mark Abley": "en.wikipedia.org/wiki/Mark_Abley", "Carolyn Abraham": "en.wikipedia.org/wiki/Carolyn_Abraham",
        "Marianne Ackerman": "en.wikipedia.org/wiki/Marianne_Ackerman",
        "Janice Acoose": "en.wikipedia.org/wiki/Janice_Acoose", "Milton Acorn": "en.wikipedia.org/wiki/Milton_Acorn",
        "José Acquelin": "en.wikipedia.org/wiki/Jos%C3%A9_Acquelin", "Ken Adachi": "en.wikipedia.org/wiki/Ken_Adachi",
        "Barry D. Adam": "en.wikipedia.org/wiki/Barry_D._Adam", "Evan Adams": "en.wikipedia.org/wiki/Evan_Adams",
        "Ian Adams": "en.wikipedia.org/wiki/Ian_Adams", "Mary Electa Adams": "en.wikipedia.org/wiki/Mary_Electa_Adams",
        "Gil Adamson": "en.wikipedia.org/wiki/Gil_Adamson",
        "Caroline Adderson": "en.wikipedia.org/wiki/Caroline_Adderson",
        "Marie-Célie Agnant": "en.wikipedia.org/wiki/Marie-C%C3%A9lie_Agnant",
        "Freda Ahenakew": "en.wikipedia.org/wiki/Freda_Ahenakew",
        "Kelley Aitken": "en.wikipedia.org/wiki/Kelley_Aitken", "Will Aitken": "en.wikipedia.org/wiki/Will_Aitken",
        "Donald Akenson": "en.wikipedia.org/wiki/Donald_Akenson",
        "Kateri Akiwenzie-Damm": "en.wikipedia.org/wiki/Kateri_Akiwenzie-Damm",
        "Linda Aksomitis": "en.wikipedia.org/wiki/Linda_Aksomitis",
        "Kamal Al-Solaylee": "en.wikipedia.org/wiki/Kamal_Al-Solaylee",
        "Donald Alarie": "en.wikipedia.org/wiki/Donald_Alarie",
        "Scott Albert": "en.wikipedia.org/wiki/Scott_Albert_(writer)",
        "Robert Arthur Alexie": "en.wikipedia.org/wiki/Robert_Arthur_Alexie",
        "André Alexis": "en.wikipedia.org/wiki/Andr%C3%A9_Alexis", "Edna Alford": "en.wikipedia.org/wiki/Edna_Alford",
        "Sandra Alland": "en.wikipedia.org/wiki/Sandra_Alland", "Donna Allard": "en.wikipedia.org/wiki/Donna_Allard",
        "Charlotte Vale Allen": "en.wikipedia.org/wiki/Charlotte_Vale_Allen",
        "Grant Allen": "en.wikipedia.org/wiki/Grant_Allen", "Harper Allen": "en.wikipedia.org/wiki/Harper_Allen",
        "Lillian Allen": "en.wikipedia.org/wiki/Lillian_Allen",
        "Ralph Allen": "en.wikipedia.org/wiki/Ralph_Allen_(journalist)",
        "Robert Thomas Allen": "en.wikipedia.org/wiki/Robert_Thomas_Allen",
        "Tom Allen": "en.wikipedia.org/wiki/Tom_Allen_(broadcaster)",
        "Paul Almond": "en.wikipedia.org/wiki/Paul_Almond",
        "Anne-Marie Alonzo": "en.wikipedia.org/wiki/Anne-Marie_Alonzo",
        "George Amabile": "en.wikipedia.org/wiki/George_Amabile", "Anahareo": "en.wikipedia.org/wiki/Anahareo",
        "Marguerite Andersen": "en.wikipedia.org/wiki/Marguerite_Andersen",
        "Debra Anderson": "en.wikipedia.org/wiki/Debra_Anderson",
        "Doris Anderson": "en.wikipedia.org/wiki/Doris_Anderson",
        "Enza Anderson": "en.wikipedia.org/wiki/Enza_Anderson",
        "Gordon Stewart Anderson": "en.wikipedia.org/wiki/Gordon_Stewart_Anderson",
        "Hugh Anderson": "en.wikipedia.org/wiki/Hugh_Abercrombie_Anderson",
        "Patrick Anderson": "en.wikipedia.org/wiki/Patrick_Anderson_(poet)",
        "Rod Anderson": "en.wikipedia.org/wiki/Rod_Anderson_(writer)",
        "Trevor Anderson": "en.wikipedia.org/wiki/Trevor_Anderson_(artist)",
        "Gail Anderson-Dargatz": "en.wikipedia.org/wiki/Gail_Anderson-Dargatz",
        "Michael Andre": "en.wikipedia.org/wiki/Michael_Andre",
        "François-Réal Angers": "en.wikipedia.org/wiki/Fran%C3%A7ois-R%C3%A9al_Angers",
        "Trey Anthony": "en.wikipedia.org/wiki/Trey_Anthony",
        "Salvatore Antonio": "en.wikipedia.org/wiki/Salvatore_Antonio",
        "Marianne Apostolides": "en.wikipedia.org/wiki/Marianne_Apostolides",
        "Lisa Appignanesi": "en.wikipedia.org/wiki/Lisa_Appignanesi",
        "Emmanuel Aquin": "en.wikipedia.org/wiki/Emmanuel_Aquin", "Hubert Aquin": "en.wikipedia.org/wiki/Hubert_Aquin",
        "Nelly Arcan": "en.wikipedia.org/wiki/Nelly_Arcan",
        "Gilles Archambault": "en.wikipedia.org/wiki/Gilles_Archambault",
        "Bert Archer": "en.wikipedia.org/wiki/Bert_Archer", "Richard Arès": "en.wikipedia.org/wiki/Richard_Ar%C3%A8s",
        "Tammy Armstrong": "en.wikipedia.org/wiki/Tammy_Armstrong",
        "Jeannette Armstrong": "en.wikipedia.org/wiki/Jeannette_Armstrong",
        "Kelley Armstrong": "en.wikipedia.org/wiki/Kelley_Armstrong",
        "Rebecca Agatha Armour": "en.wikipedia.org/wiki/Rebecca_Agatha_Armour",
        "David Arnason": "en.wikipedia.org/wiki/David_Arnason", "Joanne Arnott": "en.wikipedia.org/wiki/Joanne_Arnott",
        "Lawrence Aronovitch": "en.wikipedia.org/wiki/Lawrence_Aronovitch",
        "Nina Arsenault": "en.wikipedia.org/wiki/Nina_Arsenault",
        "Ryad Assani-Razaki": "en.wikipedia.org/wiki/Ryad_Assani-Razaki",
        "Damien Atkins": "en.wikipedia.org/wiki/Damien_Atkins",
        "Diana Atkinson": "en.wikipedia.org/wiki/Diana_Atkinson",
        "Margaret Atwood": "en.wikipedia.org/wiki/Margaret_Atwood",
        "Phillipe-Ignace François Aubert du Gaspé": "en.wikipedia.org/wiki/Phillipe-Ignace_Fran%C3%A7ois_Aubert_du_Gasp%C3%A9",
        "Philippe-Joseph Aubert de Gaspé": "en.wikipedia.org/wiki/Philippe-Joseph_Aubert_de_Gasp%C3%A9",
        "Aude": "en.wikipedia.org/wiki/Aude_(writer)", "Jean-Paul Audet": "en.wikipedia.org/wiki/Jean-Paul_Audet",
        "Jonathan Auxier": "en.wikipedia.org/wiki/Jonathan_Auxier",
        "François Avard": "en.wikipedia.org/wiki/Fran%C3%A7ois_Avard",
        "Margaret Avison": "en.wikipedia.org/wiki/Margaret_Avison", "Mona Awad": "en.wikipedia.org/wiki/Mona_Awad",
        "Edem Awumey": "en.wikipedia.org/wiki/Edem_Awumey", "Malcolm Azania": "en.wikipedia.org/wiki/Malcolm_Azania",
        "Caroline Azar": "en.wikipedia.org/wiki/Caroline_Azar", "Todd Babiak": "en.wikipedia.org/wiki/Todd_Babiak",
        "Ken Babstock": "en.wikipedia.org/wiki/Ken_Babstock", "Mette Bach": "en.wikipedia.org/wiki/Mette_Bach",
        "Elizabeth Bachinsky": "en.wikipedia.org/wiki/Elizabeth_Bachinsky",
        "Bruce Bagemihl": "en.wikipedia.org/wiki/Bruce_Bagemihl",
        "Martha Baillie": "en.wikipedia.org/wiki/Martha_Baillie",
        "Jacqueline Baker": "en.wikipedia.org/wiki/Jacqueline_Baker",
        "R. Scott Bakker": "en.wikipedia.org/wiki/R._Scott_Bakker", "Sharon Bala": "en.wikipedia.org/wiki/Sharon_Bala",
        "Shauna Singh Baldwin": "en.wikipedia.org/wiki/Shauna_Singh_Baldwin",
        "Winifred Bambrick": "en.wikipedia.org/wiki/Winifred_Bambrick",
        "Catherine Banks": "en.wikipedia.org/wiki/Catherine_Banks",
        "Himani Bannerji": "en.wikipedia.org/wiki/Himani_Bannerji",
        "Kaushalya Bannerji": "en.wikipedia.org/wiki/Kaushalya_Bannerji",
        "Gary Bannerman": "en.wikipedia.org/wiki/Gary_Bannerman", "Nick Bantock": "en.wikipedia.org/wiki/Nick_Bantock",
        "Marius Barbeau": "en.wikipedia.org/wiki/Marius_Barbeau",
        "Raymond Barbeau": "en.wikipedia.org/wiki/Raymond_Barbeau",
        "Victor Barbeau": "en.wikipedia.org/wiki/Victor_Barbeau", "Bruce Barber": "en.wikipedia.org/wiki/Bruce_Barber",
        "Joan Barfoot": "en.wikipedia.org/wiki/Joan_Barfoot",
        "Keith Barker": "en.wikipedia.org/wiki/Keith_Barker_(writer)",
        "Robert Barr": "en.wikipedia.org/wiki/Robert_Barr_(writer)",
        "Laurent Barré": "en.wikipedia.org/wiki/Laurent_Barr%C3%A9",
        "James Bartleman": "en.wikipedia.org/wiki/James_Bartleman",
        "John Barton": "en.wikipedia.org/wiki/John_Barton_(poet)", "Gary Barwin": "en.wikipedia.org/wiki/Gary_Barwin",
        "Earl W. Bascom": "en.wikipedia.org/wiki/Earl_W._Bascom",
        "Rodrigo Bascunan": "en.wikipedia.org/wiki/Rodrigo_Bascunan",
        "Jean Basile": "en.wikipedia.org/wiki/Jean_Basile",
        "Michel Basilières": "en.wikipedia.org/wiki/Michel_Basili%C3%A8res",
        "Gurjinder Basran": "en.wikipedia.org/wiki/Gurjinder_Basran",
        "Frédéric Bastien": "en.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Bastien",
        "Arjun Basu": "en.wikipedia.org/wiki/Arjun_Basu",
        "Andrew Battershill": "en.wikipedia.org/wiki/Andrew_Battershill",
        "Claire Battershill": "en.wikipedia.org/wiki/Claire_Battershill",
        "Bill Bauer": "en.wikipedia.org/wiki/Bill_Bauer_(poet)", "Nancy Bauer": "en.wikipedia.org/wiki/Nancy_Bauer",
        "Jeremy Bates": "en.wikipedia.org/wiki/Jeremy_Bates_(author)",
        "Kevin Bazzana": "en.wikipedia.org/wiki/Kevin_Bazzana",
        "Yves Beauchemin": "en.wikipedia.org/wiki/Yves_Beauchemin",
        "Victor-Lévy Beaulieu": "en.wikipedia.org/wiki/Victor-L%C3%A9vy_Beaulieu",
        "Doug Beardsley": "en.wikipedia.org/wiki/Doug_Beardsley",
        "Jeann Beattie": "en.wikipedia.org/wiki/Jeann_Beattie",
        "Deni Ellis Béchard": "en.wikipedia.org/wiki/Deni_Ellis_B%C3%A9chard",
        "Peter Behrens": "en.wikipedia.org/wiki/Peter_Behrens_(writer)",
        "Henry Beissel": "en.wikipedia.org/wiki/Henry_Beissel",
        "Billy-Ray Belcourt": "en.wikipedia.org/wiki/Billy-Ray_Belcourt",
        "Ken Belford": "en.wikipedia.org/wiki/Ken_Belford", "Donald Bell": "en.wikipedia.org/wiki/Donald_Bell_(writer)",
        "William E. Bell": "en.wikipedia.org/wiki/William_E._Bell_(author)",
        "Winthrop Pickard Bell": "en.wikipedia.org/wiki/Winthrop_Pickard_Bell",
        "Paul Bellini": "en.wikipedia.org/wiki/Paul_Bellini", "John Bemrose": "en.wikipedia.org/wiki/John_Bemrose",
        "Gwen Benaway": "en.wikipedia.org/wiki/Gwen_Benaway",
        "Djemila Benhabib": "en.wikipedia.org/wiki/Djemila_Benhabib",
        "Nigel Bennett": "en.wikipedia.org/wiki/Nigel_Bennett", "David Bergen": "en.wikipedia.org/wiki/David_Bergen",
        "S. Bear Bergman": "en.wikipedia.org/wiki/S._Bear_Bergman",
        "David Berman": "en.wikipedia.org/wiki/David_Berman_(graphic_designer)",
        "Christophe Bernard": "en.wikipedia.org/wiki/Christophe_Bernard",
        "Jovette Bernier": "en.wikipedia.org/wiki/Jovette_Bernier", "Kris Bertin": "en.wikipedia.org/wiki/Kris_Bertin",
        "Pierre Berton": "en.wikipedia.org/wiki/Pierre_Berton",
        "Dennison Berwick": "en.wikipedia.org/wiki/Dennison_Berwick",
        "Gérard Bessette": "en.wikipedia.org/wiki/G%C3%A9rard_Bessette",
        "H. S. Bhabra": "en.wikipedia.org/wiki/H._S._Bhabra", "Navtej Bharati": "en.wikipedia.org/wiki/Navtej_Bharati",
        "Dave Bidini": "en.wikipedia.org/wiki/Dave_Bidini", "Anthony Bidulka": "en.wikipedia.org/wiki/Anthony_Bidulka",
        "Nicolas Billon": "en.wikipedia.org/wiki/Nicolas_Billon",
        "Pierre Billon": "en.wikipedia.org/wiki/Pierre_Billon", "Will R. Bird": "en.wikipedia.org/wiki/Will_R._Bird",
        "Sandra Birdsell": "en.wikipedia.org/wiki/Sandra_Birdsell",
        "Earle Birney": "en.wikipedia.org/wiki/Earle_Birney",
        "Carol Bishop-Gwyn": "en.wikipedia.org/wiki/Carol_Bishop-Gwyn",
        "bill bissett": "en.wikipedia.org/wiki/Bill_bissett",
        "Lise Bissonnette": "en.wikipedia.org/wiki/Lise_Bissonnette",
        "Neil Bissoondath": "en.wikipedia.org/wiki/Neil_Bissoondath",
        "Persimmon Blackbridge": "en.wikipedia.org/wiki/Persimmon_Blackbridge",
        "George G. Blackburn": "en.wikipedia.org/wiki/George_G._Blackburn",
        "Marthe Blackburn": "en.wikipedia.org/wiki/Marthe_Blackburn",
        "Peggy Blair": "en.wikipedia.org/wiki/Peggy_Blair",
        "Marie-Claire Blais": "en.wikipedia.org/wiki/Marie-Claire_Blais",
        "Clark Blaise": "en.wikipedia.org/wiki/Clark_Blaise", "Robin Blaser": "en.wikipedia.org/wiki/Robin_Blaser",
        "Lance Blomgren": "en.wikipedia.org/wiki/Lance_Blomgren",
        "Patricia Blondal": "en.wikipedia.org/wiki/Patricia_Blondal",
        "Lise Blouin": "en.wikipedia.org/wiki/Lise_Blouin",
        "Michael Blouin": "en.wikipedia.org/wiki/Michael_Blouin_(writer)",
        "Martha Blum": "en.wikipedia.org/wiki/Martha_Blum", "Giles Blunt": "en.wikipedia.org/wiki/Giles_Blunt",
        "Ali Blythe": "en.wikipedia.org/wiki/Ali_Blythe", "Adam Bock": "en.wikipedia.org/wiki/Adam_Bock",
        "Dennis Bock": "en.wikipedia.org/wiki/Dennis_Bock",
        "Maxime Raymond Bock": "en.wikipedia.org/wiki/Maxime_Raymond_Bock",
        "Michel Bock": "en.wikipedia.org/wiki/Michel_Bock", "Fred Bodsworth": "en.wikipedia.org/wiki/Fred_Bodsworth",
        "Christian Bök": "en.wikipedia.org/wiki/Christian_B%C3%B6k",
        "Stephanie Bolster": "en.wikipedia.org/wiki/Stephanie_Bolster",
        "Carol Bolt": "en.wikipedia.org/wiki/Carol_Bolt", "Kenneth Bonert": "en.wikipedia.org/wiki/Kenneth_Bonert",
        "Shane Book": "en.wikipedia.org/wiki/Shane_Book", "Walter Borden": "en.wikipedia.org/wiki/Walter_Borden",
        "Kathryn Borel": "en.wikipedia.org/wiki/Kathryn_Borel", "Roo Borson": "en.wikipedia.org/wiki/Roo_Borson",
        "Monique Bosco": "en.wikipedia.org/wiki/Monique_Bosco",
        "Gérard Bouchard": "en.wikipedia.org/wiki/G%C3%A9rard_Bouchard",
        "Michel Marc Bouchard": "en.wikipedia.org/wiki/Michel_Marc_Bouchard",
        "Paul Bouchard": "en.wikipedia.org/wiki/Paul_Bouchard",
        "Marsha Boulton": "en.wikipedia.org/wiki/Marsha_Boulton",
        "Hédi Bouraoui": "en.wikipedia.org/wiki/H%C3%A9di_Bouraoui",
        "Pierre Bourgault": "en.wikipedia.org/wiki/Pierre_Bourgault",
        "Pan Bouyoucas": "en.wikipedia.org/wiki/Pan_Bouyoucas", "Gail Bowen": "en.wikipedia.org/wiki/Gail_Bowen",
        "George Bowering": "en.wikipedia.org/wiki/George_Bowering",
        "Marilyn Bowering": "en.wikipedia.org/wiki/Marilyn_Bowering",
        "Bonnie Bowman": "en.wikipedia.org/wiki/Bonnie_Bowman",
        "Randy Boyagoda": "en.wikipedia.org/wiki/Randy_Boyagoda",
        "David Boyd": "en.wikipedia.org/wiki/David_Boyd_(author)",
        "George Boyd": "en.wikipedia.org/wiki/George_Boyd_(playwright)",
        "Joseph Boyden": "en.wikipedia.org/wiki/Joseph_Boyden",
        "Harry J. Boyle": "en.wikipedia.org/wiki/Harry_J._Boyle",
        "Karleen Bradford": "en.wikipedia.org/wiki/Karleen_Bradford",
        "Lawrence Ytzhak Braithwaite": "en.wikipedia.org/wiki/Lawrence_Ytzhak_Braithwaite",
        "Max Braithwaite": "en.wikipedia.org/wiki/Max_Braithwaite",
        "Shannon Bramer": "en.wikipedia.org/wiki/Shannon_Bramer",
        "Alan Bradley": "en.wikipedia.org/wiki/Alan_Bradley_(writer)",
        "Dionne Brand": "en.wikipedia.org/wiki/Dionne_Brand", "Di Brandt": "en.wikipedia.org/wiki/Di_Brandt",
        "Beth Brant": "en.wikipedia.org/wiki/Beth_Brant", "André Brassard": "en.wikipedia.org/wiki/Andr%C3%A9_Brassard",
        "Marie Brassard": "en.wikipedia.org/wiki/Marie_Brassard",
        "Jacques Brault": "en.wikipedia.org/wiki/Jacques_Brault", "Lois Braun": "en.wikipedia.org/wiki/Lois_Braun",
        "Morwyn Brebner": "en.wikipedia.org/wiki/Morwyn_Brebner", "Brian Brett": "en.wikipedia.org/wiki/Brian_Brett",
        "Krista Bridge": "en.wikipedia.org/wiki/Krista_Bridge",
        "Robert Bringhurst": "en.wikipedia.org/wiki/Robert_Bringhurst",
        "Barry Broadfoot": "en.wikipedia.org/wiki/Barry_Broadfoot",
        "Hélène Brodeur": "en.wikipedia.org/wiki/H%C3%A9l%C3%A8ne_Brodeur",
        "David Bromige": "en.wikipedia.org/wiki/David_Bromige",
        "Frances Brooke": "en.wikipedia.org/wiki/Frances_Brooke",
        "Bertram Brooker": "en.wikipedia.org/wiki/Bertram_Brooker",
        "Carellin Brooks": "en.wikipedia.org/wiki/Carellin_Brooks",
        "Nicole Brossard": "en.wikipedia.org/wiki/Nicole_Brossard",
        "Chrystine Brouillet": "en.wikipedia.org/wiki/Chrystine_Brouillet",
        "Sigmund Brouwer": "en.wikipedia.org/wiki/Sigmund_Brouwer",
        "Charles Tory Bruce": "en.wikipedia.org/wiki/Charles_Tory_Bruce",
        "Julie Bruck": "en.wikipedia.org/wiki/Julie_Bruck",
        "Tyler Brûlé": "en.wikipedia.org/wiki/Tyler_Br%C3%BBl%C3%A9",
        "Gaétan Brulotte": "en.wikipedia.org/wiki/Ga%C3%A9tan_Brulotte",
        "Nick Brune": "en.wikipedia.org/wiki/Nick_Brune", "Carol Bruneau": "en.wikipedia.org/wiki/Carol_Bruneau",
        "Louis-Ovide Brunet": "en.wikipedia.org/wiki/Louis-Ovide_Brunet",
        "Michel Brunet": "en.wikipedia.org/wiki/Michel_Brunet_(historian)",
        "Cathy Marie Buchanan": "en.wikipedia.org/wiki/Cathy_Marie_Buchanan",
        "Ernest Buckler": "en.wikipedia.org/wiki/Ernest_Buckler", "Robert Budde": "en.wikipedia.org/wiki/Robert_Budde",
        "Margaret Buffie": "en.wikipedia.org/wiki/Margaret_Buffie",
        "Gilbert Buote": "en.wikipedia.org/wiki/Gilbert_Buote", "Kayt Burgess": "en.wikipedia.org/wiki/Kayt_Burgess",
        "Tony Burgess": "en.wikipedia.org/wiki/Tony_Burgess_(author)",
        "Nathan Burgoine": "en.wikipedia.org/wiki/Nathan_Burgoine",
        "Ronnie Burkett": "en.wikipedia.org/wiki/Ronnie_Burkett",
        "Mabel Burkholder": "en.wikipedia.org/wiki/Mabel_Burkholder",
        "Bonnie Burnard": "en.wikipedia.org/wiki/Bonnie_Burnard",
        "Murdoch Burnett": "en.wikipedia.org/wiki/Murdoch_Burnett",
        "Richard Burnett": "en.wikipedia.org/wiki/Richard_Burnett",
        "Lawrence J. Burpee": "en.wikipedia.org/wiki/Lawrence_Johnstone_Burpee",
        "Mick Burrs": "en.wikipedia.org/wiki/Mick_Burrs",
        "Frank Christopher Busch": "en.wikipedia.org/wiki/Frank_Christopher_Busch",
        "Catherine Bush": "en.wikipedia.org/wiki/Catherine_Bush",
        "Sharon Butala": "en.wikipedia.org/wiki/Sharon_Butala", "Alec Butler": "en.wikipedia.org/wiki/Alec_Butler",
        "Charmaine Cadeau": "en.wikipedia.org/wiki/Charmaine_Cadeau",
        "Stephen Cain": "en.wikipedia.org/wiki/Stephen_Cain_(poet)",
        "Frank Oliver Call": "en.wikipedia.org/wiki/Frank_Oliver_Call",
        "Barry Callaghan": "en.wikipedia.org/wiki/Barry_Callaghan",
        "Morley Callaghan": "en.wikipedia.org/wiki/Morley_Callaghan",
        "Anne Cameron": "en.wikipedia.org/wiki/Anne_Cameron",
        "Elspeth Cameron": "en.wikipedia.org/wiki/Elspeth_Cameron",
        "George Frederick Cameron": "en.wikipedia.org/wiki/George_Frederick_Cameron",
        "Silver Donald Cameron": "en.wikipedia.org/wiki/Silver_Donald_Cameron",
        "Natalee Caple": "en.wikipedia.org/wiki/Natalee_Caple", "Pat Capponi": "en.wikipedia.org/wiki/Pat_Capponi",
        "Opal Carew": "en.wikipedia.org/wiki/Opal_Carew", "Dave Carley": "en.wikipedia.org/wiki/Dave_Carley",
        "Louis Carmain": "en.wikipedia.org/wiki/Louis_Carmain", "Bliss Carman": "en.wikipedia.org/wiki/Bliss_Carman",
        "Louis Caron": "en.wikipedia.org/wiki/Louis_Caron",
        "David Carpenter": "en.wikipedia.org/wiki/David_Carpenter_(writer)",
        "Emily Carr": "en.wikipedia.org/wiki/Emily_Carr", "Roch Carrier": "en.wikipedia.org/wiki/Roch_Carrier",
        "Anne Carson": "en.wikipedia.org/wiki/Anne_Carson",
        "Anne Laurel Carter": "en.wikipedia.org/wiki/Anne_Laurel_Carter",
        "Allan Casey": "en.wikipedia.org/wiki/Allan_Casey", "Kate Cayley": "en.wikipedia.org/wiki/Kate_Cayley",
        "Denys Chabot": "en.wikipedia.org/wiki/Denys_Chabot", "Robert Chafe": "en.wikipedia.org/wiki/Robert_Chafe",
        "Francis Chalifour": "en.wikipedia.org/wiki/Francis_Chalifour",
        "Gillian Chan": "en.wikipedia.org/wiki/Gillian_Chan",
        "David Chariandy": "en.wikipedia.org/wiki/David_Chariandy",
        "Lyne Charlebois": "en.wikipedia.org/wiki/Lyne_Charlebois",
        "Pierre François Xavier de Charlevoix": "en.wikipedia.org/wiki/Pierre_Fran%C3%A7ois_Xavier_de_Charlevoix",
        "Normand Chaurette": "en.wikipedia.org/wiki/Normand_Chaurette",
        "Évelyne de la Chenelière": "en.wikipedia.org/wiki/%C3%89velyne_de_la_Cheneli%C3%A8re",
        "Herménégilde Chiasson": "en.wikipedia.org/wiki/Herm%C3%A9n%C3%A9gilde_Chiasson",
        "Philip Child": "en.wikipedia.org/wiki/Philip_Child", "Anne Chislett": "en.wikipedia.org/wiki/Anne_Chislett",
        "Ins Choi": "en.wikipedia.org/wiki/Ins_Choi", "Denise Chong": "en.wikipedia.org/wiki/Denise_Chong",
        "Wayson Choy": "en.wikipedia.org/wiki/Wayson_Choy", "Lesley Choyce": "en.wikipedia.org/wiki/Lesley_Choyce",
        "Michael Christie": "en.wikipedia.org/wiki/Michael_Christie_(writer)",
        "Jane Christmas": "en.wikipedia.org/wiki/Jane_Christmas",
        "Eliza Clark": "en.wikipedia.org/wiki/Eliza_Clark_(author)",
        "Greg Clark": "en.wikipedia.org/wiki/Greg_Clark_(journalist)", "Joan Clark": "en.wikipedia.org/wiki/Joan_Clark",
        "Austin Clarke": "en.wikipedia.org/wiki/Austin_Clarke_(novelist)",
        "George Elliott Clarke": "en.wikipedia.org/wiki/George_Elliott_Clarke",
        "Stéfanie Clermont": "en.wikipedia.org/wiki/St%C3%A9fanie_Clermont",
        "David Clerson": "en.wikipedia.org/wiki/David_Clerson",
        "Fabien Cloutier": "en.wikipedia.org/wiki/Fabien_Cloutier", "Lynn Coady": "en.wikipedia.org/wiki/Lynn_Coady",
        "Mark Coakley": "en.wikipedia.org/wiki/Mark_Coakley", "Fred Cogswell": "en.wikipedia.org/wiki/Fred_Cogswell",
        "Leonard Cohen": "en.wikipedia.org/wiki/Leonard_Cohen",
        "Matt Cohen": "en.wikipedia.org/wiki/Matt_Cohen_(writer)",
        "Susan G. Cole": "en.wikipedia.org/wiki/Susan_G._Cole",
        "Trevor Cole": "en.wikipedia.org/wiki/Trevor_Cole_(writer)",
        "Anne Coleman": "en.wikipedia.org/wiki/Anne_Coleman", "Victor Coleman": "en.wikipedia.org/wiki/Victor_Coleman",
        "Don Coles": "en.wikipedia.org/wiki/Don_Coles", "Ruth Collie": "en.wikipedia.org/wiki/Ruth_Collie",
        "John Robert Colombo": "en.wikipedia.org/wiki/John_Robert_Colombo",
        "Judith Copithorne": "en.wikipedia.org/wiki/Judith_Copithorne",
        "Wayde Compton": "en.wikipedia.org/wiki/Wayde_Compton", "Bill Conall": "en.wikipedia.org/wiki/Bill_Conall",
        "Jan Conn": "en.wikipedia.org/wiki/Jan_Conn", "Karen Connelly": "en.wikipedia.org/wiki/Karen_Connelly",
        "Kevin Connolly": "en.wikipedia.org/wiki/Kevin_Connolly_(writer)",
        "Ralph Connor": "en.wikipedia.org/wiki/Ralph_Connor",
        "George Ramsay Cook": "en.wikipedia.org/wiki/George_Ramsay_Cook",
        "Hugh Cook": "en.wikipedia.org/wiki/Hugh_Cook_(Canadian_novelist)",
        "Michael Cook": "en.wikipedia.org/wiki/Michael_Cook_(playwright)",
        "Tim Cook": "en.wikipedia.org/wiki/Tim_Cook_(writer)", "Dennis Cooley": "en.wikipedia.org/wiki/Dennis_Cooley",
        "Douglas Cooper": "en.wikipedia.org/wiki/Douglas_Anthony_Cooper",
        "Paige Cooper": "en.wikipedia.org/wiki/Paige_Cooper", "Ann Copeland": "en.wikipedia.org/wiki/Ann_Copeland",
        "Carole Corbeil": "en.wikipedia.org/wiki/Carole_Corbeil",
        "Charlotte Corbeil-Coleman": "en.wikipedia.org/wiki/Charlotte_Corbeil-Coleman",
        "Thomas B. Costain": "en.wikipedia.org/wiki/Thomas_B._Costain",
        "Douglas Coupland": "en.wikipedia.org/wiki/Douglas_Coupland", "Hugh Cowan": "en.wikipedia.org/wiki/Hugh_Cowan",
        "James Alexander Cowan": "en.wikipedia.org/wiki/James_Alexander_Cowan",
        "Daniel Allen Cox": "en.wikipedia.org/wiki/Daniel_Allen_Cox",
        "Ivan Coyote": "en.wikipedia.org/wiki/Ivan_Coyote", "Archie Crail": "en.wikipedia.org/wiki/Archie_Crail",
        "Isabella Valancy Crawford": "en.wikipedia.org/wiki/Isabella_Valancy_Crawford",
        "Donald Creighton": "en.wikipedia.org/wiki/Donald_Creighton",
        "Luella Creighton": "en.wikipedia.org/wiki/Luella_Creighton",
        "Octave Crémazie": "en.wikipedia.org/wiki/Octave_Cr%C3%A9mazie",
        "Eva Crocker": "en.wikipedia.org/wiki/Eva_Crocker", "Lynn Crosbie": "en.wikipedia.org/wiki/Lynn_Crosbie",
        "Lorna Crozier": "en.wikipedia.org/wiki/Lorna_Crozier",
        "Michael Crummey": "en.wikipedia.org/wiki/Michael_Crummey",
        "Nancy Jo Cullen": "en.wikipedia.org/wiki/Nancy_Jo_Cullen", "Alan Cumyn": "en.wikipedia.org/wiki/Alan_Cumyn",
        "Richard Cumyn": "en.wikipedia.org/wiki/Richard_Cumyn", "Peter Cureton": "en.wikipedia.org/wiki/Peter_Cureton",
        "Andrea Curtis": "en.wikipedia.org/wiki/Andrea_Curtis", "Herb Curtis": "en.wikipedia.org/wiki/Herb_Curtis",
        "Kayla Czaga": "en.wikipedia.org/wiki/Kayla_Czaga",
        "Antonio D'Alfonso": "en.wikipedia.org/wiki/Antonio_D%27Alfonso",
        "Anne Dandurand": "en.wikipedia.org/wiki/Anne_Dandurand", "Louis Dantin": "en.wikipedia.org/wiki/Louis_Dantin",
        "Jean-Paul Daoust": "en.wikipedia.org/wiki/Jean-Paul_Daoust",
        "Peter Darbyshire": "en.wikipedia.org/wiki/Peter_Darbyshire", "Jill Daum": "en.wikipedia.org/wiki/Jill_Daum",
        "Frank Davey": "en.wikipedia.org/wiki/Frank_Davey", "Craig Davidson": "en.wikipedia.org/wiki/Craig_Davidson",
        "True Davidson": "en.wikipedia.org/wiki/True_Davidson",
        "Robertson Davies": "en.wikipedia.org/wiki/Robertson_Davies",
        "Lauren B. Davis": "en.wikipedia.org/wiki/Lauren_B._Davis", "Amber Dawn": "en.wikipedia.org/wiki/Amber_Dawn",
        "Frank Parker Day": "en.wikipedia.org/wiki/Frank_Parker_Day",
        "Claire Dé": "en.wikipedia.org/wiki/Claire_D%C3%A9",
        "Mazo de la Roche": "en.wikipedia.org/wiki/Mazo_de_la_Roche",
        "Charles de Lint": "en.wikipedia.org/wiki/Charles_de_Lint",
        "Elisabeth de Mariaffi": "en.wikipedia.org/wiki/Elisabeth_de_Mariaffi",
        "Sadiqa de Meijer": "en.wikipedia.org/wiki/Sadiqa_de_Meijer",
        "James de Mille": "en.wikipedia.org/wiki/James_de_Mille",
        "Marq de Villiers": "en.wikipedia.org/wiki/Marq_de_Villiers",
        "Anthony de Sa": "en.wikipedia.org/wiki/Anthony_de_Sa",
        "Patrick deWitt": "en.wikipedia.org/wiki/Patrick_deWitt",
        "Michael Delisle": "en.wikipedia.org/wiki/Michael_Delisle",
        "David Demchuk": "en.wikipedia.org/wiki/David_Demchuk",
        "Sandra Dempsey": "en.wikipedia.org/wiki/Sandra_Dempsey",
        "Barry Dempster": "en.wikipedia.org/wiki/Barry_Dempster",
        "Dennis Denisoff": "en.wikipedia.org/wiki/Dennis_Denisoff",
        "Randall Denley": "en.wikipedia.org/wiki/Randall_Denley",
        "Léo-Paul Desrosiers": "en.wikipedia.org/wiki/L%C3%A9o-Paul_Desrosiers",
        "Henriette Dessaulles": "en.wikipedia.org/wiki/Henriette_Dessaulles",
        "Alexander Dewdney": "en.wikipedia.org/wiki/Alexander_Dewdney",
        "Christopher Dewdney": "en.wikipedia.org/wiki/Christopher_Dewdney",
        "Selwyn Hanington Dewdney": "en.wikipedia.org/wiki/Selwyn_Dewdney",
        "Myrna Dey": "en.wikipedia.org/wiki/Myrna_Dey", "Ranj Dhaliwal": "en.wikipedia.org/wiki/Ranj_Dhaliwal",
        "Pier Giorgio Di Cicco": "en.wikipedia.org/wiki/Pier_Giorgio_Di_Cicco",
        "Mary di Michele": "en.wikipedia.org/wiki/Mary_di_Michele", "Ann Diamond": "en.wikipedia.org/wiki/Ann_Diamond",
        "Don Dickinson": "en.wikipedia.org/wiki/Don_Dickinson",
        "Nicolas Dickner": "en.wikipedia.org/wiki/Nicolas_Dickner",
        "Cherie Dimaline": "en.wikipedia.org/wiki/Cherie_Dimaline", "Sandra Djwa": "en.wikipedia.org/wiki/Sandra_Djwa",
        "Kildare Dobbs": "en.wikipedia.org/wiki/Kildare_Dobbs",
        "Farzana Doctor": "en.wikipedia.org/wiki/Farzana_Doctor",
        "Cory Doctorow": "en.wikipedia.org/wiki/Cory_Doctorow", "Jeramy Dodds": "en.wikipedia.org/wiki/Jeramy_Dodds",
        "Bob Dolman": "en.wikipedia.org/wiki/Bob_Dolman", "Don Domanski": "en.wikipedia.org/wiki/Don_Domanski",
        "Fernand Dorais": "en.wikipedia.org/wiki/Fernand_Dorais",
        "Candas Jane Dorsey": "en.wikipedia.org/wiki/Candas_Jane_Dorsey",
        "Clive Doucet": "en.wikipedia.org/wiki/Clive_Doucet",
        "Orville Lloyd Douglas": "en.wikipedia.org/wiki/Orville_Lloyd_Douglas",
        "James Doull": "en.wikipedia.org/wiki/James_Doull", "Glen Downey": "en.wikipedia.org/wiki/Glen_Downey_(writer)",
        "Brian Doyle": "en.wikipedia.org/wiki/Brian_Doyle_(writer)",
        "Brian Drader": "en.wikipedia.org/wiki/Brian_Drader", "Stan Dragland": "en.wikipedia.org/wiki/Stan_Dragland",
        "William Henry Drummond": "en.wikipedia.org/wiki/William_Henry_Drummond",
        "Marcel Dubé": "en.wikipedia.org/wiki/Marcel_Dub%C3%A9", "Peter Dubé": "en.wikipedia.org/wiki/Peter_Dub%C3%A9",
        "Réjean Ducharme": "en.wikipedia.org/wiki/R%C3%A9jean_Ducharme",
        "Louis Dudek": "en.wikipedia.org/wiki/Louis_Dudek", "Margaret Duley": "en.wikipedia.org/wiki/Margaret_Duley",
        "Dave Duncan": "en.wikipedia.org/wiki/Dave_Duncan_(writer)",
        "Sara Jeannette Duncan": "en.wikipedia.org/wiki/Sara_Jeannette_Duncan",
        "Warren Dunford": "en.wikipedia.org/wiki/Warren_Dunford",
        "Norma Dunning": "en.wikipedia.org/wiki/Norma_Dunning",
        "Kristyn Dunnion": "en.wikipedia.org/wiki/Kristyn_Dunnion",
        "Éric Dupont": "en.wikipedia.org/wiki/%C3%89ric_Dupont_(writer)",
        "Douglas Durkin": "en.wikipedia.org/wiki/Douglas_Durkin",
        "Lawrence Earl": "en.wikipedia.org/wiki/Lawrence_Earl",
        "Edith Maude Eaton": "en.wikipedia.org/wiki/Edith_Maude_Eaton",
        "Evelyn Eaton": "en.wikipedia.org/wiki/Evelyn_Eaton",
        "Chris Eaton": "en.wikipedia.org/wiki/Chris_Eaton_(Canadian_musician)",
        "Winnifred Eaton": "en.wikipedia.org/wiki/Winnifred_Eaton_(writer)",
        "James Eayrs": "en.wikipedia.org/wiki/James_Eayrs", "Kim Echlin": "en.wikipedia.org/wiki/Kim_Echlin",
        "David Eddie": "en.wikipedia.org/wiki/David_Eddie", "Esi Edugyan": "en.wikipedia.org/wiki/Esi_Edugyan",
        "Caterina Edwards": "en.wikipedia.org/wiki/Caterina_Edwards",
        "Modris Eksteins": "en.wikipedia.org/wiki/Modris_Eksteins",
        "George Elliott": "en.wikipedia.org/wiki/George_Elliott_(Canadian_writer)",
        "Deborah Ellis": "en.wikipedia.org/wiki/Deborah_Ellis",
        "Sarah Ellis": "en.wikipedia.org/wiki/Sarah_Ellis_(author)",
        "Louis Émond": "en.wikipedia.org/wiki/Louis_%C3%89mond",
        "Marina Endicott": "en.wikipedia.org/wiki/Marina_Endicott",
        "Howard Engel": "en.wikipedia.org/wiki/Howard_Engel", "Marian Engel": "en.wikipedia.org/wiki/Marian_Engel",
        "Yves Engler": "en.wikipedia.org/wiki/Yves_Engler", "Sharon English": "en.wikipedia.org/wiki/Sharon_English",
        "Steven Erikson": "en.wikipedia.org/wiki/Steven_Erikson", "Ann Eriksson": "en.wikipedia.org/wiki/Ann_Eriksson",
        "Gloria Escomel": "en.wikipedia.org/wiki/Gloria_Escomel",
        "Michael Estok": "en.wikipedia.org/wiki/Michael_Estok",
        "Hubert Evans": "en.wikipedia.org/wiki/Hubert_Evans_(author)",
        "Jon Evans": "en.wikipedia.org/wiki/Jon_Evans_(author)",
        "Stanley Evans": "en.wikipedia.org/wiki/Stanley_Evans_(author)",
        "Emil Fackenheim": "en.wikipedia.org/wiki/Emil_Fackenheim",
        "Terry Fallis": "en.wikipedia.org/wiki/Terry_Fallis", "Alain Farah": "en.wikipedia.org/wiki/Alain_Farah",
        "Edmundo Farolan": "en.wikipedia.org/wiki/Edmundo_Farolan",
        "Brian Fawcett": "en.wikipedia.org/wiki/Brian_Fawcett",
        "Charles Fenerty": "en.wikipedia.org/wiki/Charles_Fenerty",
        "Ian Ferguson": "en.wikipedia.org/wiki/Ian_Ferguson_(writer)",
        "Max Ferguson": "en.wikipedia.org/wiki/Max_Ferguson",
        "Trevor Ferguson": "en.wikipedia.org/wiki/Trevor_Ferguson",
        "Will Ferguson": "en.wikipedia.org/wiki/Will_Ferguson",
        "Jacques Ferron": "en.wikipedia.org/wiki/Jacques_Ferron",
        "Madeleine Ferron": "en.wikipedia.org/wiki/Madeleine_Ferron",
        "George Fetherling": "en.wikipedia.org/wiki/George_Fetherling",
        "Charlotte Fielden": "en.wikipedia.org/wiki/Charlotte_Fielden",
        "Joy Fielding": "en.wikipedia.org/wiki/Joy_Fielding", "Connie Fife": "en.wikipedia.org/wiki/Connie_Fife",
        "Timothy Findley": "en.wikipedia.org/wiki/Timothy_Findley", "Lois Fine": "en.wikipedia.org/wiki/Lois_Fine",
        "Larry Fineberg": "en.wikipedia.org/wiki/Larry_Fineberg", "Joe Fiorito": "en.wikipedia.org/wiki/Joe_Fiorito",
        "Sheree Fitch": "en.wikipedia.org/wiki/Sheree_Fitch",
        "James FitzGerald": "en.wikipedia.org/wiki/James_FitzGerald_(writer)",
        "Judith Fitzgerald": "en.wikipedia.org/wiki/Judith_Fitzgerald",
        "Anne Fleming": "en.wikipedia.org/wiki/Anne_Fleming_(writer)",
        "May Agnes Fleming": "en.wikipedia.org/wiki/May_Agnes_Fleming",
        "Cynthia Flood": "en.wikipedia.org/wiki/Cynthia_Flood", "Lisa Foad": "en.wikipedia.org/wiki/Lisa_Foad",
        "Waawaate Fobister": "en.wikipedia.org/wiki/Waawaate_Fobister",
        "Jacques Folch-Ribas": "en.wikipedia.org/wiki/Jacques_Folch-Ribas",
        "Dennis Foon": "en.wikipedia.org/wiki/Dennis_Foon", "Charles Foran": "en.wikipedia.org/wiki/Charles_Foran",
        "John-James Ford": "en.wikipedia.org/wiki/John-James_Ford",
        "Helen Forrester": "en.wikipedia.org/wiki/Helen_Forrester",
        "Dominique Fortier": "en.wikipedia.org/wiki/Dominique_Fortier",
        "Cecil Foster": "en.wikipedia.org/wiki/Cecil_Foster",
        "Marion Foster": "en.wikipedia.org/wiki/Marion_Foster_(writer)",
        "Roger Fournier": "en.wikipedia.org/wiki/Roger_Fournier",
        "Barbara Fradkin": "en.wikipedia.org/wiki/Barbara_Fradkin",
        "Tess Fragoulis": "en.wikipedia.org/wiki/Tess_Fragoulis",
        "Brian Francis": "en.wikipedia.org/wiki/Brian_Francis", "Brad Fraser": "en.wikipedia.org/wiki/Brad_Fraser",
        "John Anderson Fraser": "en.wikipedia.org/wiki/John_Anderson_Fraser",
        "Keath Fraser": "en.wikipedia.org/wiki/Keath_Fraser", "Raymond Fraser": "en.wikipedia.org/wiki/Raymond_Fraser",
        "Sylvia Fraser": "en.wikipedia.org/wiki/Sylvia_Fraser",
        "Louis Fréchette": "en.wikipedia.org/wiki/Louis_Fr%C3%A9chette",
        "David French": "en.wikipedia.org/wiki/David_French_(playwright)",
        "Maida Parlow French": "en.wikipedia.org/wiki/Maida_Parlow_French",
        "Patrick Friesen": "en.wikipedia.org/wiki/Patrick_Friesen",
        "Mark Frutkin": "en.wikipedia.org/wiki/Mark_Frutkin", "Northrop Frye": "en.wikipedia.org/wiki/Northrop_Frye",
        "Kim Fu": "en.wikipedia.org/wiki/Kim_Fu", "Robert Fulford": "en.wikipedia.org/wiki/Robert_Fulford_(journalist)",
        "Janine Fuller": "en.wikipedia.org/wiki/Janine_Fuller", "Wes Funk": "en.wikipedia.org/wiki/Wes_Funk",
        "Nicola Furlong": "en.wikipedia.org/wiki/Nicola_Furlong", "Brendan Gall": "en.wikipedia.org/wiki/Brendan_Gall",
        "Mavis Gallant": "en.wikipedia.org/wiki/Mavis_Gallant",
        "Steven Galloway": "en.wikipedia.org/wiki/Steven_Galloway",
        "François-Xavier Garneau": "en.wikipedia.org/wiki/Fran%C3%A7ois-Xavier_Garneau",
        "Saint-Denys Garneau": "en.wikipedia.org/wiki/Saint-Denys_Garneau",
        "Hugh Garner": "en.wikipedia.org/wiki/Hugh_Garner", "Alfred Garrioch": "en.wikipedia.org/wiki/Alfred_Garrioch",
        "Elyse Gasco": "en.wikipedia.org/wiki/Elyse_Gasco", "Bill Gaston": "en.wikipedia.org/wiki/Bill_Gaston",
        "C. E. Gatchalian": "en.wikipedia.org/wiki/C._E._Gatchalian",
        "Connie Gault": "en.wikipedia.org/wiki/Connie_Gault",
        "Daniel Gawthrop": "en.wikipedia.org/wiki/Daniel_Gawthrop_(writer)",
        "Pauline Gedge": "en.wikipedia.org/wiki/Pauline_Gedge",
        "Karoline Georges": "en.wikipedia.org/wiki/Karoline_Georges",
        "Camilla Gibb": "en.wikipedia.org/wiki/Camilla_Gibb",
        "John Murray Gibbon": "en.wikipedia.org/wiki/John_Murray_Gibbon",
        "Douglas Gibson": "en.wikipedia.org/wiki/Douglas_Gibson",
        "Graeme Gibson": "en.wikipedia.org/wiki/Graeme_Gibson",
        "Margaret Gibson": "en.wikipedia.org/wiki/Margaret_Gibson_(writer)",
        "William Gibson": "en.wikipedia.org/wiki/William_Gibson", "Sky Gilbert": "en.wikipedia.org/wiki/Sky_Gilbert",
        "Charlotte Gill": "en.wikipedia.org/wiki/Charlotte_Gill",
        "John Patrick Gillese": "en.wikipedia.org/wiki/John_Patrick_Gillese",
        "David Gilmour": "en.wikipedia.org/wiki/David_Gilmour_(writer)",
        "M-E Girard": "en.wikipedia.org/wiki/M-E_Girard", "Joanna Glass": "en.wikipedia.org/wiki/Joanna_Glass",
        "John Glassco": "en.wikipedia.org/wiki/John_Glassco", "Paul Glennon": "en.wikipedia.org/wiki/Paul_Glennon",
        "Susan Glickman": "en.wikipedia.org/wiki/Susan_Glickman",
        "Douglas Glover": "en.wikipedia.org/wiki/Douglas_Glover_(writer)",
        "Jacques Godbout": "en.wikipedia.org/wiki/Jacques_Godbout",
        "Dave Godfrey": "en.wikipedia.org/wiki/Dave_Godfrey",
        "Glenda Goertzen": "en.wikipedia.org/wiki/Glenda_Goertzen",
        "Oliver Goldsmith": "en.wikipedia.org/wiki/Oliver_Goldsmith_(Canadian_poet)",
        "Gabriella Goliger": "en.wikipedia.org/wiki/Gabriella_Goliger", "Leona Gom": "en.wikipedia.org/wiki/Leona_Gom",
        "Alison Gordon": "en.wikipedia.org/wiki/Alison_Gordon",
        "Charles Gordon": "en.wikipedia.org/wiki/Charles_Gordon_(journalist)",
        "Phyllis Gotlieb": "en.wikipedia.org/wiki/Phyllis_Gotlieb",
        "Sondra Gotlieb": "en.wikipedia.org/wiki/Sondra_Gotlieb", "Hiromi Goto": "en.wikipedia.org/wiki/Hiromi_Goto",
        "John Gould": "en.wikipedia.org/wiki/John_Gould_(Canadian_writer)",
        "Nora Gould": "en.wikipedia.org/wiki/Nora_Gould",
        "George R. D. Goulet": "en.wikipedia.org/wiki/George_R._D._Goulet",
        "Terry Goulet": "en.wikipedia.org/wiki/Terry_Goulet",
        "Katherine Govier": "en.wikipedia.org/wiki/Katherine_Govier", "Lee Gowan": "en.wikipedia.org/wiki/Lee_Gowan",
        "Barbara Gowdy": "en.wikipedia.org/wiki/Barbara_Gowdy",
        "Wayne Grady": "en.wikipedia.org/wiki/Wayne_Grady_(author)",
        "Gwethalyn Graham": "en.wikipedia.org/wiki/Gwethalyn_Graham",
        "Neile Graham": "en.wikipedia.org/wiki/Neile_Graham",
        "Martin Allerdale Grainger": "en.wikipedia.org/wiki/Martin_Allerdale_Grainger",
        "Jack Granatstein": "en.wikipedia.org/wiki/Jack_Granatstein",
        "E. M. Granger Bennett": "en.wikipedia.org/wiki/E._M._Granger_Bennett",
        "George Grant": "en.wikipedia.org/wiki/George_Grant_(philosopher)",
        "Jessica Grant": "en.wikipedia.org/wiki/Jessica_Grant",
        "Charlotte Gray": "en.wikipedia.org/wiki/Charlotte_Gray_(author)",
        "R. W. Gray": "en.wikipedia.org/wiki/R._W._Gray", "Ethel Grayson": "en.wikipedia.org/wiki/Ethel_Grayson",
        "Nick Green": "en.wikipedia.org/wiki/Nick_Green_(writer)",
        "Robert Joseph Greene": "en.wikipedia.org/wiki/Robert_Joseph_Greene",
        "Ed Greenwood": "en.wikipedia.org/wiki/Ed_Greenwood", "Darren Greer": "en.wikipedia.org/wiki/Darren_Greer",
        "Daniel Grenier": "en.wikipedia.org/wiki/Daniel_Grenier",
        "Taras Grescoe": "en.wikipedia.org/wiki/Taras_Grescoe", "Grey Owl": "en.wikipedia.org/wiki/Grey_Owl",
        "Claude-Henri Grignon": "en.wikipedia.org/wiki/Claude-Henri_Grignon",
        "Lionel Groulx": "en.wikipedia.org/wiki/Lionel_Groulx",
        "Frederick Phillip Grove": "en.wikipedia.org/wiki/Frederick_Phillip_Grove",
        "Brett Josef Grubisic": "en.wikipedia.org/wiki/Brett_Josef_Grubisic",
        "Katia Grubisic": "en.wikipedia.org/wiki/Katia_Grubisic",
        "Agnès Gruda": "en.wikipedia.org/wiki/Agn%C3%A8s_Gruda",
        "Christian Guay-Poliquin": "en.wikipedia.org/wiki/Christian_Guay-Poliquin",
        "Germaine Guèvremont": "en.wikipedia.org/wiki/Germaine_Gu%C3%A8vremont",
        "Genni Gunn": "en.wikipedia.org/wiki/Genni_Gunn",
        "Kristjana Gunnars": "en.wikipedia.org/wiki/Kristjana_Gunnars",
        "David Gurr": "en.wikipedia.org/wiki/David_Gurr", "Ralph Gustafson": "en.wikipedia.org/wiki/Ralph_Gustafson",
        "Don Gutteridge": "en.wikipedia.org/wiki/Don_Gutteridge_(writer)",
        "Sandra Gwyn": "en.wikipedia.org/wiki/Sandra_Gwyn", "Rawi Hage": "en.wikipedia.org/wiki/Rawi_Hage",
        "Joan Haggerty": "en.wikipedia.org/wiki/Joan_Haggerty",
        "Roderick Haig-Brown": "en.wikipedia.org/wiki/Roderick_Haig-Brown",
        "Arthur Hailey": "en.wikipedia.org/wiki/Arthur_Hailey",
        "Thomas Chandler Haliburton": "en.wikipedia.org/wiki/Thomas_Chandler_Haliburton",
        "Louis Hamelin": "en.wikipedia.org/wiki/Louis_Hamelin",
        "Ian Hamilton": "en.wikipedia.org/wiki/Ian_Hamilton_(writer)",
        "Jane Eaton Hamilton": "en.wikipedia.org/wiki/Jane_Eaton_Hamilton",
        "Lyn Hancock": "en.wikipedia.org/wiki/Lyn_Hancock", "Angeline Hango": "en.wikipedia.org/wiki/Angeline_Hango",
        "Kevin Hardcastle": "en.wikipedia.org/wiki/Kevin_Hardcastle",
        "Robin Hardy": "en.wikipedia.org/wiki/Robin_Hardy_(Canadian_writer)",
        "Robert Harlow": "en.wikipedia.org/wiki/Robert_Harlow_(writer)",
        "Alexander Harris": "en.wikipedia.org/wiki/Alexander_Harris_(writer)",
        "Claire Harris": "en.wikipedia.org/wiki/Claire_Harris",
        "Dorothy Joan Harris": "en.wikipedia.org/wiki/Dorothy_Joan_Harris",
        "Marjorie Harris": "en.wikipedia.org/wiki/Marjorie_Harris",
        "Michael Harris": "en.wikipedia.org/wiki/Michael_Harris_(editor)",
        "Keith Harrison": "en.wikipedia.org/wiki/Keith_Harrison", "Jill Hartman": "en.wikipedia.org/wiki/Jill_Hartman",
        "Diana Hartog": "en.wikipedia.org/wiki/Diana_Hartog",
        "Kristen den Hartog": "en.wikipedia.org/wiki/Kristen_den_Hartog",
        "Kenneth J. Harvey": "en.wikipedia.org/wiki/Kenneth_J._Harvey",
        "Elisabeth Harvor": "en.wikipedia.org/wiki/Elisabeth_Harvor",
        "Liedewy Hawke": "en.wikipedia.org/wiki/Liedewy_Hawke",
        "Barbara Haworth-Attard": "en.wikipedia.org/wiki/Barbara_Haworth-Attard",
        "Elizabeth Hay": "en.wikipedia.org/wiki/Elizabeth_Hay_(novelist)",
        "Elliott Hayes": "en.wikipedia.org/wiki/Elliott_Hayes", "Matthew Hays": "en.wikipedia.org/wiki/Matthew_Hays",
        "Steven Hayward": "en.wikipedia.org/wiki/Steven_Hayward_(Canadian_writer)",
        "Charles Heavysege": "en.wikipedia.org/wiki/Charles_Heavysege",
        "Anne Hébert": "en.wikipedia.org/wiki/Anne_H%C3%A9bert",
        "Steven Heighton": "en.wikipedia.org/wiki/Steven_Heighton",
        "William C. Heine": "en.wikipedia.org/wiki/William_C._Heine",
        "Matthew Heiti": "en.wikipedia.org/wiki/Matthew_Heiti", "Michael Helm": "en.wikipedia.org/wiki/Michael_Helm",
        "David Helwig": "en.wikipedia.org/wiki/David_Helwig", "Maggie Helwig": "en.wikipedia.org/wiki/Maggie_Helwig",
        "Louis Hémon": "en.wikipedia.org/wiki/Louis_H%C3%A9mon", "Sarah Henstra": "en.wikipedia.org/wiki/Sarah_Henstra",
        "John Herbert": "en.wikipedia.org/wiki/John_Herbert_(playwright)",
        "Catherine Hernandez": "en.wikipedia.org/wiki/Catherine_Hernandez",
        "Trevor Herriot": "en.wikipedia.org/wiki/Trevor_Herriot",
        "Benjamin Hertwig": "en.wikipedia.org/wiki/Benjamin_Hertwig",
        "Sheila Heti": "en.wikipedia.org/wiki/Sheila_Heti",
        "Paul Hiebert": "en.wikipedia.org/wiki/Paul_Hiebert_(writer)",
        "Tomson Highway": "en.wikipedia.org/wiki/Tomson_Highway",
        "Lawrence Hill": "en.wikipedia.org/wiki/Lawrence_Hill", "Ernest Hillen": "en.wikipedia.org/wiki/Ernest_Hillen",
        "Robert Hilles": "en.wikipedia.org/wiki/Robert_Hilles", "Jack Hodgins": "en.wikipedia.org/wiki/Jack_Hodgins",
        "Susan Holbrook": "en.wikipedia.org/wiki/Susan_Holbrook",
        "Arthur Holden": "en.wikipedia.org/wiki/Arthur_Holden", "Clive Holden": "en.wikipedia.org/wiki/Clive_Holden",
        "Claire Holden Rothman": "en.wikipedia.org/wiki/Claire_Holden_Rothman",
        "Pauline Holdstock": "en.wikipedia.org/wiki/Pauline_Holdstock",
        "Greg Hollingshead": "en.wikipedia.org/wiki/Greg_Hollingshead",
        "Margaret Hollingsworth": "en.wikipedia.org/wiki/Margaret_Hollingsworth",
        "Michael Hollingsworth": "en.wikipedia.org/wiki/Michael_Hollingsworth_(writer)",
        "Nancy Holmes": "en.wikipedia.org/wiki/Nancy_Holmes",
        "Margaret Lindsay Holton": "en.wikipedia.org/wiki/Margaret_Lindsay_Holton",
        "Hugh Hood": "en.wikipedia.org/wiki/Hugh_Hood", "Cornelia Hoogland": "en.wikipedia.org/wiki/Cornelia_Hoogland",
        "Emma Hooper": "en.wikipedia.org/wiki/Emma_Hooper", "Nalo Hopkinson": "en.wikipedia.org/wiki/Nalo_Hopkinson",
        "Leah Horlick": "en.wikipedia.org/wiki/Leah_Horlick", "Harold Horwood": "en.wikipedia.org/wiki/Harold_Horwood",
        "Liz Howard": "en.wikipedia.org/wiki/Liz_Howard_(writer)", "Tanya Huff": "en.wikipedia.org/wiki/Tanya_Huff",
        "Matt Hughes": "en.wikipedia.org/wiki/Matt_Hughes_(writer)",
        "Helen Humphreys": "en.wikipedia.org/wiki/Helen_Humphreys",
        "Aislinn Hunter": "en.wikipedia.org/wiki/Aislinn_Hunter",
        "Bruce Hunter": "en.wikipedia.org/wiki/Bruce_Hunter_(poet)",
        "Catherine Hunter": "en.wikipedia.org/wiki/Catherine_Hunter",
        "Maureen Hunter": "en.wikipedia.org/wiki/Maureen_Hunter",
        "Mervyn Huston": "en.wikipedia.org/wiki/Mervyn_Huston", "Nancy Huston": "en.wikipedia.org/wiki/Nancy_Huston",
        "Linda Hutcheon": "en.wikipedia.org/wiki/Linda_Hutcheon",
        "Hazel Hutchins": "en.wikipedia.org/wiki/Hazel_Hutchins",
        "Chris Hutchinson": "en.wikipedia.org/wiki/Chris_Hutchinson_(poet)",
        "Bruce Hutchison": "en.wikipedia.org/wiki/Bruce_Hutchison",
        "Joel Thomas Hynes": "en.wikipedia.org/wiki/Joel_Thomas_Hynes",
        "Maureen Hynes": "en.wikipedia.org/wiki/Maureen_Hynes", "Ameer Idreis": "en.wikipedia.org/wiki/Ameer_Idreis",
        "Michael Ignatieff": "en.wikipedia.org/wiki/Michael_Ignatieff",
        "George K. Ilsley": "en.wikipedia.org/wiki/George_K._Ilsley",
        "Neamat Imam": "en.wikipedia.org/wiki/Neamat_Imam", "Susan Ioannou": "en.wikipedia.org/wiki/Susan_Ioannou",
        "Anosh Irani": "en.wikipedia.org/wiki/Anosh_Irani", "Ann Ireland": "en.wikipedia.org/wiki/Ann_Ireland",
        "Adel Iskandar": "en.wikipedia.org/wiki/Adel_Iskandar", "Frances Itani": "en.wikipedia.org/wiki/Frances_Itani",
        "Donald Jack": "en.wikipedia.org/wiki/Donald_Jack", "Suzanne Jacob": "en.wikipedia.org/wiki/Suzanne_Jacob",
        "Candice James": "en.wikipedia.org/wiki/Candice_James",
        "Anna Brownell Jameson": "en.wikipedia.org/wiki/Anna_Brownell_Jameson",
        "J. Robert Janes": "en.wikipedia.org/wiki/J._Robert_Janes",
        "Mark Anthony Jarman": "en.wikipedia.org/wiki/Mark_Anthony_Jarman",
        "Melynda Jarratt": "en.wikipedia.org/wiki/Melynda_Jarratt",
        "François Jeanneret": "en.wikipedia.org/wiki/Fran%C3%A7ois_Charles_Archile_Jeanneret",
        "Paulette Jiles": "en.wikipedia.org/wiki/Paulette_Jiles",
        "K.V. Johansen": "en.wikipedia.org/wiki/K.V._Johansen", "Linda Johns": "en.wikipedia.org/wiki/Linda_Johns",
        "E. Pauline Johnson": "en.wikipedia.org/wiki/E._Pauline_Johnson",
        "Wentworth M. Johnson": "en.wikipedia.org/wiki/Wentworth_M._Johnson",
        "Aviaq Johnston": "en.wikipedia.org/wiki/Aviaq_Johnston",
        "Julie Johnston": "en.wikipedia.org/wiki/Julie_Johnston_(writer)",
        "Wayne Johnston": "en.wikipedia.org/wiki/Wayne_Johnston_(writer)",
        "Sean Johnston": "en.wikipedia.org/wiki/Sean_Johnston",
        "Andy Jones": "en.wikipedia.org/wiki/Andy_Jones_(comedian)", "D. G. Jones": "en.wikipedia.org/wiki/D._G._Jones",
        "Terry Jordan": "en.wikipedia.org/wiki/Terry_Jordan_(Canadian_writer)",
        "Michael Kaan": "en.wikipedia.org/wiki/Michael_Kaan",
        "Elaine Kalman Naves": "en.wikipedia.org/wiki/Elaine_Kalman_Naves",
        "Surjeet Kalsey": "en.wikipedia.org/wiki/Surjeet_Kalsey",
        "Smaro Kamboureli": "en.wikipedia.org/wiki/Smaro_Kamboureli",
        "Alan Kane": "en.wikipedia.org/wiki/Alan_Kane_(author)",
        "Adeena Karasick": "en.wikipedia.org/wiki/Adeena_Karasick", "Ibi Kaslik": "en.wikipedia.org/wiki/Ibi_Kaslik",
        "Welwyn Wilton Katz": "en.wikipedia.org/wiki/Welwyn_Wilton_Katz",
        "Guy Gavriel Kay": "en.wikipedia.org/wiki/Guy_Gavriel_Kay",
        "Greg Kearney": "en.wikipedia.org/wiki/Greg_Kearney", "Lionel Kearns": "en.wikipedia.org/wiki/Lionel_Kearns",
        "Diane Keating": "en.wikipedia.org/wiki/Diane_Keating", "Julie Keith": "en.wikipedia.org/wiki/Julie_Keith",
        "Thomas P. Kelley": "en.wikipedia.org/wiki/Thomas_P._Kelley",
        "M. T. Kelly": "en.wikipedia.org/wiki/M._T._Kelly", "Sean Kelly": "en.wikipedia.org/wiki/Sean_Kelly_(writer)",
        "Olivier Kemeid": "en.wikipedia.org/wiki/Olivier_Kemeid",
        "Howard Angus Kennedy": "en.wikipedia.org/wiki/Howard_Angus_Kennedy",
        "Michael Kenyon": "en.wikipedia.org/wiki/Michael_Kenyon_(Canadian_writer)",
        "Susan Kerslake": "en.wikipedia.org/wiki/Susan_Kerslake",
        "Joseph Kertes": "en.wikipedia.org/wiki/Joseph_Kertes",
        "William Kilbourn": "en.wikipedia.org/wiki/William_Kilbourn",
        "Crawford Kilian": "en.wikipedia.org/wiki/Crawford_Kilian",
        "Crad Kilodney": "en.wikipedia.org/wiki/Crad_Kilodney",
        "Deborah Kimmett": "en.wikipedia.org/wiki/Deborah_Kimmett", "Basil King": "en.wikipedia.org/wiki/Basil_King",
        "Thomas King": "en.wikipedia.org/wiki/Thomas_King_(novelist)",
        "Mark Kingwell": "en.wikipedia.org/wiki/Mark_Kingwell", "W.P. Kinsella": "en.wikipedia.org/wiki/W.P._Kinsella",
        "William Kirby": "en.wikipedia.org/wiki/William_Kirby_(author)",
        "Barbara Klar": "en.wikipedia.org/wiki/Barbara_Klar", "Sarah Klassen": "en.wikipedia.org/wiki/Sarah_Klassen",
        "A. M. Klein": "en.wikipedia.org/wiki/A._M._Klein", "Joshua Knelman": "en.wikipedia.org/wiki/Joshua_Knelman",
        "Raymond Knister": "en.wikipedia.org/wiki/Raymond_Knister",
        "Alexander Knox": "en.wikipedia.org/wiki/Alexander_Knox",
        "Tamai Kobayashi": "en.wikipedia.org/wiki/Tamai_Kobayashi", "Eric Koch": "en.wikipedia.org/wiki/Eric_Koch",
        "Joy Kogawa": "en.wikipedia.org/wiki/Joy_Kogawa",
        "Miodrag Kojadinović": "en.wikipedia.org/wiki/Miodrag_Kojadinovi%C4%87",
        "Sergio Kokis": "en.wikipedia.org/wiki/Sergio_Kokis", "Gordon Korman": "en.wikipedia.org/wiki/Gordon_Korman",
        "Myrna Kostash": "en.wikipedia.org/wiki/Myrna_Kostash", "Shane Koyczan": "en.wikipedia.org/wiki/Shane_Koyczan",
        "Greg Kramer": "en.wikipedia.org/wiki/Greg_Kramer", "Philip Kreiner": "en.wikipedia.org/wiki/Philip_Kreiner",
        "Henry Kreisel": "en.wikipedia.org/wiki/Henry_Kreisel", "John Krizanc": "en.wikipedia.org/wiki/John_Krizanc",
        "Robert Kroetsch": "en.wikipedia.org/wiki/Robert_Kroetsch",
        "Kathryn Kuitenbrouwer": "en.wikipedia.org/wiki/Kathryn_Kuitenbrouwer",
        "Janice Kulyk Keefer": "en.wikipedia.org/wiki/Janice_Kulyk_Keefer",
        "J. D. Kurtness": "en.wikipedia.org/wiki/J._D._Kurtness",
        "Michael Kusugak": "en.wikipedia.org/wiki/Michael_Kusugak", "Lydia Kwa": "en.wikipedia.org/wiki/Lydia_Kwa",
        "Sonnet L'Abbé": "en.wikipedia.org/wiki/Sonnet_L%27Abb%C3%A9",
        "Richard Labonté": "en.wikipedia.org/wiki/Richard_Labont%C3%A9",
        "Rosa Labordé": "en.wikipedia.org/wiki/Rosa_Labord%C3%A9",
        "Marie-Sissi Labrèche": "en.wikipedia.org/wiki/Marie-Sissi_Labr%C3%A8che",
        "Edward A. Lacey": "en.wikipedia.org/wiki/Edward_A._Lacey",
        "Ben Ladouceur": "en.wikipedia.org/wiki/Ben_Ladouceur",
        "Steven Laffoley": "en.wikipedia.org/wiki/Steven_Laffoley", "Larissa Lai": "en.wikipedia.org/wiki/Larissa_Lai",
        "Vincent Lam": "en.wikipedia.org/wiki/Vincent_Lam", "Gerald Lampert": "en.wikipedia.org/wiki/Gerald_Lampert",
        "Tim Lander": "en.wikipedia.org/wiki/Tim_Lander", "Patrick Lane": "en.wikipedia.org/wiki/Patrick_Lane",
        "André Langevin": "en.wikipedia.org/wiki/Andr%C3%A9_Langevin",
        "Marisa Lankester": "en.wikipedia.org/wiki/Marisa_Lankester",
        "Shari Lapena": "en.wikipedia.org/wiki/Shari_Lapena",
        "Annette Lapointe": "en.wikipedia.org/wiki/Annette_Lapointe",
        "Gilbert La Rocque": "en.wikipedia.org/wiki/Gilbert_La_Rocque",
        "Stéphane Larue": "en.wikipedia.org/wiki/St%C3%A9phane_Larue", "Evelyn Lau": "en.wikipedia.org/wiki/Evelyn_Lau",
        "Margaret Laurence": "en.wikipedia.org/wiki/Margaret_Laurence",
        "Agnes C. Laut": "en.wikipedia.org/wiki/Agnes_Christina_Laut",
        "Karen Lawrence": "en.wikipedia.org/wiki/Karen_Lawrence_(writer)",
        "R.D. Lawrence": "en.wikipedia.org/wiki/R.D._Lawrence", "Mary Lawson": "en.wikipedia.org/wiki/Mary_Lawson",
        "Irving Layton": "en.wikipedia.org/wiki/Irving_Layton", "Jack Layton": "en.wikipedia.org/wiki/Jack_Layton",
        "Stephen Leacock": "en.wikipedia.org/wiki/Stephen_Leacock",
        "Perrine Leblanc": "en.wikipedia.org/wiki/Perrine_Leblanc",
        "D. M. LeBourdais": "en.wikipedia.org/wiki/D._M._LeBourdais",
        "Isabel LeBourdais": "en.wikipedia.org/wiki/Isabel_LeBourdais",
        "Félix Leclerc": "en.wikipedia.org/wiki/F%C3%A9lix_Leclerc",
        "Dennis Lee": "en.wikipedia.org/wiki/Dennis_Lee_(author)",
        "John Alan Lee": "en.wikipedia.org/wiki/John_Alan_Lee", "JJ Lee": "en.wikipedia.org/wiki/JJ_Lee_(writer)",
        "Jen Sookfong Lee": "en.wikipedia.org/wiki/Jen_Sookfong_Lee",
        "John B. Lee": "en.wikipedia.org/wiki/John_B._Lee", "Nancy Lee": "en.wikipedia.org/wiki/Nancy_Lee_(writer)",
        "Ronald Lee": "en.wikipedia.org/wiki/Ronald_Lee", "Sky Lee": "en.wikipedia.org/wiki/Sky_Lee",
        "Mathyas Lefebure": "en.wikipedia.org/wiki/Mathyas_Lefebure",
        "Lily Alice Lefevre": "en.wikipedia.org/wiki/Lily_Alice_Lefevre",
        "Mark Leiren-Young": "en.wikipedia.org/wiki/Mark_Leiren-Young",
        "Roger Lemelin": "en.wikipedia.org/wiki/Roger_Lemelin", "Matt Lennox": "en.wikipedia.org/wiki/Matt_Lennox",
        "John Lent": "en.wikipedia.org/wiki/John_Lent", "Don LePan": "en.wikipedia.org/wiki/Don_LePan",
        "Douglas LePan": "en.wikipedia.org/wiki/Douglas_LePan",
        "Catherine Leroux": "en.wikipedia.org/wiki/Catherine_Leroux",
        "Pierre Leroux": "en.wikipedia.org/wiki/Pierre_Leroux_(author)",
        "Alex Leslie": "en.wikipedia.org/wiki/Alex_Leslie", "Mark Leslie": "en.wikipedia.org/wiki/Mark_Leslie_(author)",
        "Norman Levine": "en.wikipedia.org/wiki/Norman_Levine", "Shar Levine": "en.wikipedia.org/wiki/Shar_Levine",
        "Naomi K. Lewis": "en.wikipedia.org/wiki/Naomi_K._Lewis",
        "Wyndham Lewis": "en.wikipedia.org/wiki/Wyndham_Lewis", "Thea Lim": "en.wikipedia.org/wiki/Thea_Lim",
        "Michael Lista": "en.wikipedia.org/wiki/Michael_Lista", "Ashley Little": "en.wikipedia.org/wiki/Ashley_Little",
        "Jean Little": "en.wikipedia.org/wiki/Jean_Little", "Dorothy Livesay": "en.wikipedia.org/wiki/Dorothy_Livesay",
        "Billie Livingston": "en.wikipedia.org/wiki/Billie_Livingston",
        "Douglas Lochhead": "en.wikipedia.org/wiki/Douglas_Lochhead",
        "Lynette Loeppky": "en.wikipedia.org/wiki/Lynette_Loeppky",
        "Kevin Loring": "en.wikipedia.org/wiki/Kevin_Loring",
        "Jennifer LoveGrove": "en.wikipedia.org/wiki/Jennifer_LoveGrove",
        "Malcolm Lowry": "en.wikipedia.org/wiki/Malcolm_Lowry", "Pat Lowther": "en.wikipedia.org/wiki/Pat_Lowther",
        "Jack Ludwig": "en.wikipedia.org/wiki/Jack_Ludwig", "Pearl Luke": "en.wikipedia.org/wiki/Pearl_Luke",
        "Janet Lunn": "en.wikipedia.org/wiki/Janet_Lunn", "Laura Lush": "en.wikipedia.org/wiki/Laura_Lush",
        "Richard Lush": "en.wikipedia.org/wiki/Richard_Lush_(writer)",
        "Michael Lynch": "en.wikipedia.org/wiki/Michael_Lynch_(professor)",
        "Annabel Lyon": "en.wikipedia.org/wiki/Annabel_Lyon", "Eswyn Lyster": "en.wikipedia.org/wiki/Eswyn_Lyster",
        "Rozena Maart": "en.wikipedia.org/wiki/Rozena_Maart",
        "Patrick MacAdam": "en.wikipedia.org/wiki/Patrick_MacAdam",
        "Agnes Maule Machar": "en.wikipedia.org/wiki/Agnes_Maule_Machar",
        "Ann-Marie MacDonald": "en.wikipedia.org/wiki/Ann-Marie_MacDonald",
        "Bryden MacDonald": "en.wikipedia.org/wiki/Bryden_MacDonald",
        "D. R. MacDonald": "en.wikipedia.org/wiki/D._R._MacDonald",
        "Hugh MacDonald": "en.wikipedia.org/wiki/Hugh_MacDonald_(poet)",
        "Jake MacDonald": "en.wikipedia.org/wiki/Jake_MacDonald",
        "Janice MacDonald": "en.wikipedia.org/wiki/Janice_MacDonald",
        "Maggie MacDonald": "en.wikipedia.org/wiki/Maggie_MacDonald",
        "Wilson MacDonald": "en.wikipedia.org/wiki/Wilson_MacDonald",
        "Lee MacDougall": "en.wikipedia.org/wiki/Lee_MacDougall",
        "Gwendolyn MacEwen": "en.wikipedia.org/wiki/Gwendolyn_MacEwen",
        "Mary Esther MacGregor": "en.wikipedia.org/wiki/Mary_Esther_MacGregor",
        "Roy MacGregor": "en.wikipedia.org/wiki/Roy_MacGregor",
        "Linden MacIntyre": "en.wikipedia.org/wiki/Linden_MacIntyre",
        "Rory Maclean": "en.wikipedia.org/wiki/Rory_Maclean", "Hugh MacLennan": "en.wikipedia.org/wiki/Hugh_MacLennan",
        "Matt MacLennan": "en.wikipedia.org/wiki/Matt_MacLennan",
        "Michael MacLennan": "en.wikipedia.org/wiki/Michael_MacLennan",
        "Alexander MacLeod": "en.wikipedia.org/wiki/Alexander_MacLeod_(writer)",
        "Alison MacLeod": "en.wikipedia.org/wiki/Alison_MacLeod",
        "Alistair MacLeod": "en.wikipedia.org/wiki/Alistair_MacLeod",
        "Elizabeth Macleod": "en.wikipedia.org/wiki/Elizabeth_Macleod",
        "Joan MacLeod": "en.wikipedia.org/wiki/Joan_MacLeod", "Rick Maddocks": "en.wikipedia.org/wiki/Rick_Maddocks",
        "Adriana Maggs": "en.wikipedia.org/wiki/Adriana_Maggs", "Randall Maggs": "en.wikipedia.org/wiki/Randall_Maggs",
        "Anand Mahadevan": "en.wikipedia.org/wiki/Anand_Mahadevan",
        "Rabindranath Maharaj": "en.wikipedia.org/wiki/Rabindranath_Maharaj",
        "Louise Maheux-Forcier": "en.wikipedia.org/wiki/Louise_Maheux-Forcier",
        "Keith Maillard": "en.wikipedia.org/wiki/Keith_Maillard",
        "Antonine Maillet": "en.wikipedia.org/wiki/Antonine_Maillet",
        "André Major": "en.wikipedia.org/wiki/Andr%C3%A9_Major", "Kevin Major": "en.wikipedia.org/wiki/Kevin_Major",
        "Pasha Malla": "en.wikipedia.org/wiki/Pasha_Malla", "Donato Mancini": "en.wikipedia.org/wiki/Donato_Mancini",
        "Eli Mandel": "en.wikipedia.org/wiki/Eli_Mandel", "Miriam Mandel": "en.wikipedia.org/wiki/Miriam_Mandel",
        "Avner Mandelman": "en.wikipedia.org/wiki/Avner_Mandelman",
        "David Manicom": "en.wikipedia.org/wiki/David_Manicom", "Lee Maracle": "en.wikipedia.org/wiki/Lee_Maracle",
        "Blaine Marchand": "en.wikipedia.org/wiki/Blaine_Marchand",
        "Jovette Marchessault": "en.wikipedia.org/wiki/Jovette_Marchessault",
        "Robert Marinier": "en.wikipedia.org/wiki/Robert_Marinier",
        "Daphne Marlatt": "en.wikipedia.org/wiki/Daphne_Marlatt", "Paul Marlowe": "en.wikipedia.org/wiki/Paul_Marlowe",
        "John Marlyn": "en.wikipedia.org/wiki/John_Marlyn", "Nicole Markotic": "en.wikipedia.org/wiki/Nicole_Markotic",
        "Tom Marshall": "en.wikipedia.org/wiki/Tom_Marshall_(poet)",
        "Émile Martel": "en.wikipedia.org/wiki/%C3%89mile_Martel_(writer)",
        "Yann Martel": "en.wikipedia.org/wiki/Yann_Martel", "Camille Martin": "en.wikipedia.org/wiki/Camille_Martin",
        "Claire Martin": "en.wikipedia.org/wiki/Claire_Martin_(writer)",
        "Paul Nicholas Mason": "en.wikipedia.org/wiki/Paul_Nicholas_Mason",
        "Vincent Massey": "en.wikipedia.org/wiki/Vincent_Massey", "Elan Mastai": "en.wikipedia.org/wiki/Elan_Mastai",
        "Carol Matas": "en.wikipedia.org/wiki/Carol_Matas",
        "Shirlee Smith Matheson": "en.wikipedia.org/wiki/Shirlee_Smith_Matheson",
        "John Bentley Mays": "en.wikipedia.org/wiki/John_Bentley_Mays",
        "Susan Mayse": "en.wikipedia.org/wiki/Susan_Mayse", "Julie Mazzieri": "en.wikipedia.org/wiki/Julie_Mazzieri",
        "Tawiah M'carthy": "en.wikipedia.org/wiki/Tawiah_M%27carthy",
        "Colin McAdam": "en.wikipedia.org/wiki/Colin_McAdam_(novelist)",
        "Steve McCaffery": "en.wikipedia.org/wiki/Steve_McCaffery",
        "Julia McCarthy": "en.wikipedia.org/wiki/Julia_McCarthy",
        "Nellie McClung": "en.wikipedia.org/wiki/Nellie_McClung",
        "Derek McCormack": "en.wikipedia.org/wiki/Derek_McCormack_(writer)",
        "Eric McCormack": "en.wikipedia.org/wiki/Eric_McCormack_(writer)",
        "Edward McCourt": "en.wikipedia.org/wiki/Edward_McCourt", "John McCrae": "en.wikipedia.org/wiki/John_McCrae",
        "Kathleen McCracken": "en.wikipedia.org/wiki/Kathleen_McCracken",
        "Derek McCulloch": "en.wikipedia.org/wiki/Derek_McCulloch_(comics)",
        "Thomas McCulloch": "en.wikipedia.org/wiki/Thomas_McCulloch",
        "Colin McDougall": "en.wikipedia.org/wiki/Colin_McDougall",
        "Franklin D. McDowell": "en.wikipedia.org/wiki/Franklin_D._McDowell",
        "Jaimie McEvoy": "en.wikipedia.org/wiki/Jaimie_McEvoy",
        "David McFadden": "en.wikipedia.org/wiki/David_McFadden_(poet)",
        "Donna McFarlane": "en.wikipedia.org/wiki/Donna_McFarlane_(writer)",
        "Leslie McFarlane": "en.wikipedia.org/wiki/Leslie_McFarlane",
        "Franklin W. Dixon": "en.wikipedia.org/wiki/Franklin_W._Dixon",
        "Sheryl McFarlane": "en.wikipedia.org/wiki/Sheryl_McFarlane",
        "Oonah McFee": "en.wikipedia.org/wiki/Oonah_McFee", "Peter McGehee": "en.wikipedia.org/wiki/Peter_McGehee",
        "Jean McIlwraith": "en.wikipedia.org/wiki/Jean_McIlwraith",
        "Edgar McInnis": "en.wikipedia.org/wiki/Edgar_McInnis",
        "James McIntyre": "en.wikipedia.org/wiki/James_McIntyre_(poet)", "Ami McKay": "en.wikipedia.org/wiki/Ami_McKay",
        "Don McKay": "en.wikipedia.org/wiki/Don_McKay", "Leo McKay, Jr.": "en.wikipedia.org/wiki/Leo_McKay,_Jr.",
        "Bruce Alistair McKelvie": "en.wikipedia.org/wiki/Bruce_Alistair_McKelvie",
        "Ian McLachlan": "en.wikipedia.org/wiki/Ian_McLachlan_(writer)",
        "Stuart McLean": "en.wikipedia.org/wiki/Stuart_McLean",
        "Marshall McLuhan": "en.wikipedia.org/wiki/Marshall_McLuhan",
        "Susan McMaster": "en.wikipedia.org/wiki/Susan_McMaster",
        "Sylvia McNicoll": "en.wikipedia.org/wiki/Sylvia_McNicoll",
        "Marie McPhedran": "en.wikipedia.org/wiki/Marie_McPhedran",
        "Christopher Meades": "en.wikipedia.org/wiki/Christopher_Meades",
        "John Melady": "en.wikipedia.org/wiki/John_Melady", "Lee Mellor": "en.wikipedia.org/wiki/Lee_Mellor",
        "Judith Merril": "en.wikipedia.org/wiki/Judith_Merril",
        "Edmund Metatawabin": "en.wikipedia.org/wiki/Edmund_Metatawabin",
        "John Metcalf": "en.wikipedia.org/wiki/John_Metcalf_(writer)", "Sarah Mian": "en.wikipedia.org/wiki/Sarah_Mian",
        "Anne Michaels": "en.wikipedia.org/wiki/Anne_Michaels",
        "Sean Michaels": "en.wikipedia.org/wiki/Sean_Michaels_(writer)",
        "Andrée A. Michaud": "en.wikipedia.org/wiki/Andr%C3%A9e_A._Michaud",
        "Stevie Mikayne": "en.wikipedia.org/wiki/Stevie_Mikayne", "Roy Miki": "en.wikipedia.org/wiki/Roy_Miki",
        "Ron Miksha": "en.wikipedia.org/wiki/Ron_Miksha", "Eleanor Millard": "en.wikipedia.org/wiki/Eleanor_Millard",
        "John Miller": "en.wikipedia.org/wiki/John_Miller_(writer)", "Orlo Miller": "en.wikipedia.org/wiki/Orlo_Miller",
        "Kenneth G. Mills": "en.wikipedia.org/wiki/Kenneth_G._Mills",
        "Christine Miscione": "en.wikipedia.org/wiki/Christine_Miscione",
        "Christian Mistral": "en.wikipedia.org/wiki/Christian_Mistral",
        "Rohinton Mistry": "en.wikipedia.org/wiki/Rohinton_Mistry",
        "Jared Mitchell": "en.wikipedia.org/wiki/Jared_Mitchell_(writer)",
        "W.O. Mitchell": "en.wikipedia.org/wiki/W.O._Mitchell",
        "Lucy Maud Montgomery": "en.wikipedia.org/wiki/Lucy_Maud_Montgomery",
        "Susanna Moodie": "en.wikipedia.org/wiki/Susanna_Moodie",
        "Brian Moore": "en.wikipedia.org/wiki/Brian_Moore_(novelist)",
        "Christopher G. Moore": "en.wikipedia.org/wiki/Christopher_G._Moore",
        "Lisa Moore": "en.wikipedia.org/wiki/Lisa_Moore_(writer)",
        "Jeffrey Moore": "en.wikipedia.org/wiki/Jeffrey_Moore_(author)",
        "Shani Mootoo": "en.wikipedia.org/wiki/Shani_Mootoo",
        "Edythe Morahan de Lauzon": "en.wikipedia.org/wiki/Edythe_Morahan_de_Lauzon",
        "Pierre Morency": "en.wikipedia.org/wiki/Pierre_Morency",
        "Bernice Morgan": "en.wikipedia.org/wiki/Bernice_Morgan",
        "Dwayne Morgan": "en.wikipedia.org/wiki/Dwayne_Morgan",
        "Grace Jones Morgan": "en.wikipedia.org/wiki/Grace_Jones_Morgan",
        "Jeffrey Morgan": "en.wikipedia.org/wiki/Jeffrey_Morgan_(writer)",
        "Tara Lee Morin": "en.wikipedia.org/wiki/Tara_Lee_Morin",
        "Guillaume Morissette": "en.wikipedia.org/wiki/Guillaume_Morissette",
        "Kim Moritsugu": "en.wikipedia.org/wiki/Kim_Moritsugu",
        "Donna Morrissey": "en.wikipedia.org/wiki/Donna_Morrissey",
        "Kim Morrissey": "en.wikipedia.org/wiki/Kim_Morrissey",
        "Garry Thomas Morse": "en.wikipedia.org/wiki/Garry_Thomas_Morse",
        "Colin Morton": "en.wikipedia.org/wiki/Colin_Morton", "Marie Moser": "en.wikipedia.org/wiki/Marie_Moser",
        "Daniel David Moses": "en.wikipedia.org/wiki/Daniel_David_Moses",
        "Tara Moss": "en.wikipedia.org/wiki/Tara_Moss", "Erin Mouré": "en.wikipedia.org/wiki/Erin_Mour%C3%A9",
        "Farley Mowat": "en.wikipedia.org/wiki/Farley_Mowat",
        "Claire Mulligan": "en.wikipedia.org/wiki/Claire_Mulligan", "Alice Munro": "en.wikipedia.org/wiki/Alice_Munro",
        "Jim Munroe": "en.wikipedia.org/wiki/Jim_Munroe", "Robert Munsch": "en.wikipedia.org/wiki/Robert_Munsch",
        "George Murray": "en.wikipedia.org/wiki/George_Murray_(poet)",
        "John Murrell": "en.wikipedia.org/wiki/John_Murrell_(playwright)",
        "Susan Musgrave": "en.wikipedia.org/wiki/Susan_Musgrave", "Maria Mutch": "en.wikipedia.org/wiki/Maria_Mutch",
        "Ira Nadel": "en.wikipedia.org/wiki/Ira_Nadel", "Hasan Namir": "en.wikipedia.org/wiki/Hasan_Namir",
        "Shenaaz Nanji": "en.wikipedia.org/wiki/Shenaaz_Nanji",
        "Mitiarjuk Nappaaluk": "en.wikipedia.org/wiki/Mitiarjuk_Nappaaluk",
        "Akhtar Naraghi": "en.wikipedia.org/wiki/Akhtar_Naraghi", "Angela Narth": "en.wikipedia.org/wiki/Angela_Narth",
        "Riel Nason": "en.wikipedia.org/wiki/Riel_Nason",
        "Michael Nathanson": "en.wikipedia.org/wiki/Michael_Nathanson", "Jen Neale": "en.wikipedia.org/wiki/Jen_Neale",
        "Émile Nelligan": "en.wikipedia.org/wiki/%C3%89mile_Nelligan", "Max Nemni": "en.wikipedia.org/wiki/Max_Nemni",
        "Monique Nemni": "en.wikipedia.org/wiki/Monique_Nemni", "Pierre Nepveu": "en.wikipedia.org/wiki/Pierre_Nepveu",
        "Sylvain Neuvel": "en.wikipedia.org/wiki/Sylvain_Neuvel", "John Newlove": "en.wikipedia.org/wiki/John_Newlove",
        "Peter C. Newman": "en.wikipedia.org/wiki/Peter_C._Newman", "bpNichol": "en.wikipedia.org/wiki/BpNichol",
        "Cecily Nicholson": "en.wikipedia.org/wiki/Cecily_Nicholson",
        "Hal Niedzviecki": "en.wikipedia.org/wiki/Hal_Niedzviecki",
        "Susin Nielsen": "en.wikipedia.org/wiki/Susin_Nielsen",
        "Frederick Niven": "en.wikipedia.org/wiki/Frederick_Niven",
        "Fraser Nixon": "en.wikipedia.org/wiki/Fraser_Nixon",
        "Francine Noël": "en.wikipedia.org/wiki/Francine_No%C3%ABl",
        "Henri Nouwen": "en.wikipedia.org/wiki/Henri_Nouwen", "Mary Novik": "en.wikipedia.org/wiki/Mary_Novik",
        "Alden Nowlan": "en.wikipedia.org/wiki/Alden_Nowlan",
        "Sheldon Oberman": "en.wikipedia.org/wiki/Sheldon_Oberman",
        "Theodore Odrach": "en.wikipedia.org/wiki/Theodore_Odrach",
        "Rohan O'Grady": "en.wikipedia.org/wiki/Rohan_O%27Grady", "Alix Ohlin": "en.wikipedia.org/wiki/Alix_Ohlin",
        "Alexandra Oliver": "en.wikipedia.org/wiki/Alexandra_Oliver",
        "Bryan Lee O'Malley": "en.wikipedia.org/wiki/Bryan_Lee_O%27Malley",
        "Heather O'Neill": "en.wikipedia.org/wiki/Heather_O%27Neill",
        "Michael Ondaatje": "en.wikipedia.org/wiki/Michael_Ondaatje",
        "Christopher Ondaatje": "en.wikipedia.org/wiki/Christopher_Ondaatje",
        "Kenneth Oppel": "en.wikipedia.org/wiki/Kenneth_Oppel",
        "Stephen Osborne": "en.wikipedia.org/wiki/Stephen_Osborne_(writer)",
        "Martha Ostenso": "en.wikipedia.org/wiki/Martha_Ostenso",
        "Lawrence O'Toole": "en.wikipedia.org/wiki/Lawrence_O%27Toole_(journalist)",
        "Fernand Ouellette": "en.wikipedia.org/wiki/Fernand_Ouellette",
        "James Macdonald Oxley": "en.wikipedia.org/wiki/James_Macdonald_Oxley",
        "Frank L. Packard": "en.wikipedia.org/wiki/Frank_L._Packard",
        "Susan Paddon": "en.wikipedia.org/wiki/Susan_Paddon", "P. K. Page": "en.wikipedia.org/wiki/P._K._Page",
        "Basil Papademos": "en.wikipedia.org/wiki/Basil_Papademos",
        "Aaron Paquette": "en.wikipedia.org/wiki/Aaron_Paquette",
        "Arleen Paré": "en.wikipedia.org/wiki/Arleen_Par%C3%A9", "Erna Paris": "en.wikipedia.org/wiki/Erna_Paris",
        "Gilbert Parker": "en.wikipedia.org/wiki/Gilbert_Parker",
        "Jocelyn Parr": "en.wikipedia.org/wiki/Jocelyn_Parr_(writer)",
        "Amanda Parris": "en.wikipedia.org/wiki/Amanda_Parris",
        "Markoosie Patsauq": "en.wikipedia.org/wiki/Markoosie_Patsauq",
        "Kevin Patterson": "en.wikipedia.org/wiki/Kevin_Patterson_(writer)",
        "Michael Patterson": "en.wikipedia.org/wiki/Michael_Patterson",
        "Raymond M. Patterson": "en.wikipedia.org/wiki/Raymond_M._Patterson",
        "Philip Kevin Paul": "en.wikipedia.org/wiki/Philip_Kevin_Paul",
        "Soraya Peerbaye": "en.wikipedia.org/wiki/Soraya_Peerbaye",
        "Francine Pelletier": "en.wikipedia.org/wiki/Francine_Pelletier_(writer)",
        "Fred Pellerin": "en.wikipedia.org/wiki/Fred_Pellerin",
        "Karleen Pendleton Jiménez": "en.wikipedia.org/wiki/Karleen_Pendleton_Jim%C3%A9nez",
        "Louise Penny": "en.wikipedia.org/wiki/Louise_Penny", "H. R. Percy": "en.wikipedia.org/wiki/H._R._Percy",
        "Susan Perly": "en.wikipedia.org/wiki/Susan_Perly", "Len Peterson": "en.wikipedia.org/wiki/Len_Peterson",
        "Zoey Leigh Peterson": "en.wikipedia.org/wiki/Zoey_Leigh_Peterson",
        "Geneviève Pettersen": "en.wikipedia.org/wiki/Genevi%C3%A8ve_Pettersen",
        "Josephine Phelan": "en.wikipedia.org/wiki/Josephine_Phelan",
        "Wendy Phillips": "en.wikipedia.org/wiki/Wendy_Phillips_(author)",
        "Lorne Pierce": "en.wikipedia.org/wiki/Lorne_Pierce",
        "Joseph Jomo Pierre": "en.wikipedia.org/wiki/Joseph_Jomo_Pierre",
        "Sarah Pinder": "en.wikipedia.org/wiki/Sarah_Pinder", "Joseph Pivato": "en.wikipedia.org/wiki/Joseph_Pivato",
        "Michel Pleau": "en.wikipedia.org/wiki/Michel_Pleau", "Casey Plett": "en.wikipedia.org/wiki/Casey_Plett",
        "Craig Poile": "en.wikipedia.org/wiki/Craig_Poile", "Daniel Poliquin": "en.wikipedia.org/wiki/Daniel_Poliquin",
        "Sharon Pollock": "en.wikipedia.org/wiki/Sharon_Pollock",
        "Michael Poole": "en.wikipedia.org/wiki/Michael_Poole_(producer)",
        "Liza Potvin": "en.wikipedia.org/wiki/Liza_Potvin", "Jacques Poulin": "en.wikipedia.org/wiki/Jacques_Poulin",
        "Christine Pountney": "en.wikipedia.org/wiki/Christine_Pountney",
        "Joël Pourbaix": "en.wikipedia.org/wiki/Jo%C3%ABl_Pourbaix", "B.W. Powe": "en.wikipedia.org/wiki/B.W._Powe",
        "Kerry Lee Powell": "en.wikipedia.org/wiki/Kerry_Lee_Powell",
        "Craig Francis Power": "en.wikipedia.org/wiki/Craig_Francis_Power",
        "E. J. Pratt": "en.wikipedia.org/wiki/E._J._Pratt",
        "Steven Price": "en.wikipedia.org/wiki/Steven_Price_(writer)",
        "Robert Priest": "en.wikipedia.org/wiki/Robert_Priest",
        "Kate Pullinger": "en.wikipedia.org/wiki/Kate_Pullinger", "Al Purdy": "en.wikipedia.org/wiki/Al_Purdy",
        "Andrew Pyper": "en.wikipedia.org/wiki/Andrew_Pyper",
        "Rachel Qitsualik-Tinsley": "en.wikipedia.org/wiki/Rachel_Qitsualik-Tinsley",
        "Sean Qitsualik-Tinsley": "en.wikipedia.org/wiki/Sean_Qitsualik-Tinsley",
        "Darlene Quaife": "en.wikipedia.org/wiki/Darlene_Quaife", "Andy Quan": "en.wikipedia.org/wiki/Andy_Quan",
        "Paul Quarrington": "en.wikipedia.org/wiki/Paul_Quarrington",
        "Meredith Quartermain": "en.wikipedia.org/wiki/Meredith_Quartermain",
        "Sina Queyras": "en.wikipedia.org/wiki/Sina_Queyras",
        "Pascale Quiviger": "en.wikipedia.org/wiki/Pascale_Quiviger",
        "Tom Rachman": "en.wikipedia.org/wiki/Tom_Rachman",
        "Thomas Head Raddall": "en.wikipedia.org/wiki/Thomas_Head_Raddall",
        "Kenneth Radu": "en.wikipedia.org/wiki/Kenneth_Radu",
        "Nasrin Rahimieh": "en.wikipedia.org/wiki/Nasrin_Rahimieh",
        "Ahmad Danny Ramadan": "en.wikipedia.org/wiki/Ahmad_Danny_Ramadan",
        "Gurcharan Rampuri": "en.wikipedia.org/wiki/Gurcharan_Rampuri",
        "Edeet Ravel": "en.wikipedia.org/wiki/Edeet_Ravel", "Angela Rawlings": "en.wikipedia.org/wiki/Angela_Rawlings",
        "Mark A. Rayner": "en.wikipedia.org/wiki/Mark_A._Rayner", "James Reaney": "en.wikipedia.org/wiki/James_Reaney",
        "Kelly Rebar": "en.wikipedia.org/wiki/Kelly_Rebar", "Duke Redbird": "en.wikipedia.org/wiki/Duke_Redbird",
        "Corey Redekop": "en.wikipedia.org/wiki/Corey_Redekop",
        "Michael Redhill": "en.wikipedia.org/wiki/Michael_Redhill",
        "Roberta Rees": "en.wikipedia.org/wiki/Roberta_Rees", "Iain Reid": "en.wikipedia.org/wiki/Iain_Reid",
        "Gayla Reid": "en.wikipedia.org/wiki/Gayla_Reid", "Raziel Reid": "en.wikipedia.org/wiki/Raziel_Reid",
        "Stephen Reid": "en.wikipedia.org/wiki/Stephen_Reid_(writer)", "Kati Rekai": "en.wikipedia.org/wiki/Kati_Rekai",
        "Shane Rhodes": "en.wikipedia.org/wiki/Shane_Rhodes",
        "François Ricard": "en.wikipedia.org/wiki/Fran%C3%A7ois_Ricard",
        "Nino Ricci": "en.wikipedia.org/wiki/Nino_Ricci",
        "David Adams Richards": "en.wikipedia.org/wiki/David_Adams_Richards",
        "Evelyn M. Richardson": "en.wikipedia.org/wiki/Evelyn_M._Richardson",
        "Jael Richardson": "en.wikipedia.org/wiki/Jael_Richardson",
        "John Richardson": "en.wikipedia.org/wiki/John_Richardson_(author)",
        "Edward Riche": "en.wikipedia.org/wiki/Edward_Riche", "Daniel Richler": "en.wikipedia.org/wiki/Daniel_Richler",
        "Emma Richler": "en.wikipedia.org/wiki/Emma_Richler", "Jacob Richler": "en.wikipedia.org/wiki/Jacob_Richler",
        "Mordecai Richler": "en.wikipedia.org/wiki/Mordecai_Richler",
        "Nancy Richler": "en.wikipedia.org/wiki/Nancy_Richler", "Noah Richler": "en.wikipedia.org/wiki/Noah_Richler",
        "Tanis Rideout": "en.wikipedia.org/wiki/Tanis_Rideout",
        "T. F. Rigelhof": "en.wikipedia.org/wiki/T._F._Rigelhof", "Sharon Riis": "en.wikipedia.org/wiki/Sharon_Riis",
        "Ringuet": "en.wikipedia.org/wiki/Ringuet",
        "Charles Ritchie": "en.wikipedia.org/wiki/Charles_Ritchie_(diplomat)",
        "Thomas Beattie Roberton": "en.wikipedia.org/wiki/Thomas_Beattie_Roberton",
        "Charles G.D. Roberts": "en.wikipedia.org/wiki/Charles_G.D._Roberts",
        "Ken Roberts": "en.wikipedia.org/wiki/Ken_Roberts_(author)",
        "Paul William Roberts": "en.wikipedia.org/wiki/Paul_William_Roberts",
        "Bill Robertson": "en.wikipedia.org/wiki/Bill_Robertson_(director)",
        "Lisa Robertson": "en.wikipedia.org/wiki/Lisa_Robertson_(poet)",
        "Margaret Murray Robertson": "en.wikipedia.org/wiki/Margaret_Murray_Robertson",
        "John Daniel Robins": "en.wikipedia.org/wiki/John_Robins_(writer)",
        "Eden Robinson": "en.wikipedia.org/wiki/Eden_Robinson",
        "J. Jill Robinson": "en.wikipedia.org/wiki/J._Jill_Robinson",
        "Peter Robinson": "en.wikipedia.org/wiki/Peter_Robinson_(novelist)",
        "Harriet A. Roche": "en.wikipedia.org/wiki/Harriet_A._Roche", "Ajmer Rode": "en.wikipedia.org/wiki/Ajmer_Rode",
        "Spider Robinson": "en.wikipedia.org/wiki/Spider_Robinson",
        "Grace Dean Rogers": "en.wikipedia.org/wiki/Grace_Dean_Rogers",
        "Ian Rogers": "en.wikipedia.org/wiki/Ian_Rogers_(writer)", "Linda Rogers": "en.wikipedia.org/wiki/Linda_Rogers",
        "Richard Rohmer": "en.wikipedia.org/wiki/Richard_Rohmer", "Leon Rooke": "en.wikipedia.org/wiki/Leon_Rooke",
        "Patrick Roscoe": "en.wikipedia.org/wiki/Patrick_Roscoe", "Rachel Rose": "en.wikipedia.org/wiki/Rachel_Rose",
        "Simon Rose": "en.wikipedia.org/wiki/Simon_Rose_(author)",
        "Rebecca Rosenblum": "en.wikipedia.org/wiki/Rebecca_Rosenblum",
        "Leonard Rosmarin": "en.wikipedia.org/wiki/Leonard_Rosmarin",
        "Sinclair Ross": "en.wikipedia.org/wiki/Sinclair_Ross", "Stuart Ross": "en.wikipedia.org/wiki/Stuart_Ross",
        "Nancy-Gay Rotstein": "en.wikipedia.org/wiki/Nancy-Gay_Rotstein",
        "Jeffrey Round": "en.wikipedia.org/wiki/Jeffrey_Round",
        "Andrea Routley": "en.wikipedia.org/wiki/Andrea_Routley",
        "André Roy": "en.wikipedia.org/wiki/Andr%C3%A9_Roy_(writer)",
        "Gabrielle Roy": "en.wikipedia.org/wiki/Gabrielle_Roy",
        "Holley Rubinsky": "en.wikipedia.org/wiki/Holley_Rubinsky", "Jane Rule": "en.wikipedia.org/wiki/Jane_Rule",
        "Alexei Maxim Russell": "en.wikipedia.org/wiki/Alexei_Maxim_Russell",
        "Elizabeth Ruth": "en.wikipedia.org/wiki/Elizabeth_Ruth",
        "Naben Ruthnum": "en.wikipedia.org/wiki/Naben_Ruthnum", "Garry Ryan": "en.wikipedia.org/wiki/Garry_Ryan",
        "George Ryga": "en.wikipedia.org/wiki/George_Ryga", "Geoff Ryman": "en.wikipedia.org/wiki/Geoff_Ryman",
        "Michelle Sagara": "en.wikipedia.org/wiki/Michelle_Sagara",
        "Donna-Michelle St. Bernard": "en.wikipedia.org/wiki/Donna-Michelle_St._Bernard",
        "Rodney Saint-Éloi": "en.wikipedia.org/wiki/Rodney_Saint-%C3%89loi",
        "Kerri Sakamoto": "en.wikipedia.org/wiki/Kerri_Sakamoto",
        "Mark Sakamoto": "en.wikipedia.org/wiki/Mark_Sakamoto", "Trish Salah": "en.wikipedia.org/wiki/Trish_Salah",
        "G. Herbert Sallans": "en.wikipedia.org/wiki/G._Herbert_Sallans",
        "Rick Salutin": "en.wikipedia.org/wiki/Rick_Salutin",
        "Laura G. Salverson": "en.wikipedia.org/wiki/Laura_G._Salverson",
        "Shelly Sanders": "en.wikipedia.org/wiki/Shelly_Sanders", "Robyn Sarah": "en.wikipedia.org/wiki/Robyn_Sarah",
        "Mairuth Sarsfield": "en.wikipedia.org/wiki/Mairuth_Sarsfield",
        "Jocelyne Saucier": "en.wikipedia.org/wiki/Jocelyne_Saucier",
        "John Ralston Saul": "en.wikipedia.org/wiki/John_Ralston_Saul",
        "Gloria Sawai": "en.wikipedia.org/wiki/Gloria_Sawai",
        "Robert J. Sawyer": "en.wikipedia.org/wiki/Robert_J._Sawyer",
        "Dominique Scali": "en.wikipedia.org/wiki/Dominique_Scali", "Alan Scarfe": "en.wikipedia.org/wiki/Alan_Scarfe",
        "Jacob Scheier": "en.wikipedia.org/wiki/Jacob_Scheier", "Libby Scheier": "en.wikipedia.org/wiki/Libby_Scheier",
        "Diane Schoemperlen": "en.wikipedia.org/wiki/Diane_Schoemperlen",
        "Stephen Scobie": "en.wikipedia.org/wiki/Stephen_Scobie",
        "Anakana Schofield": "en.wikipedia.org/wiki/Anakana_Schofield",
        "Adam Lewis Schroeder": "en.wikipedia.org/wiki/Adam_Lewis_Schroeder",
        "Andreas Schroeder": "en.wikipedia.org/wiki/Andreas_Schroeder",
        "Gregory Scofield": "en.wikipedia.org/wiki/Gregory_Scofield",
        "Chris Scott": "en.wikipedia.org/wiki/Chris_Scott_(writer)",
        "Duncan Campbell Scott": "en.wikipedia.org/wiki/Duncan_Campbell_Scott",
        "Frank Scott": "en.wikipedia.org/wiki/F._R._Scott", "Gail Scott": "en.wikipedia.org/wiki/Gail_Scott_(writer)",
        "Jordan Scott": "en.wikipedia.org/wiki/Jordan_Scott_(poet)",
        "R.T.M. Scott": "en.wikipedia.org/wiki/R.T.M._Scott",
        "Richard Scrimger": "en.wikipedia.org/wiki/Richard_Scrimger",
        "Djanet Sears": "en.wikipedia.org/wiki/Djanet_Sears",
        "Paul Seesequasis": "en.wikipedia.org/wiki/Paul_Seesequasis",
        "Benjamin Sehene": "en.wikipedia.org/wiki/Benjamin_Sehene",
        "Sarah Selecky": "en.wikipedia.org/wiki/Sarah_Selecky", "Bev Sellars": "en.wikipedia.org/wiki/Bev_Sellars",
        "Shyam Selvadurai": "en.wikipedia.org/wiki/Shyam_Selvadurai",
        "Bruce Serafin": "en.wikipedia.org/wiki/Bruce_Serafin",
        "Robert W. Service": "en.wikipedia.org/wiki/Robert_W._Service",
        "Ernest Thompson Seton": "en.wikipedia.org/wiki/Ernest_Thompson_Seton",
        "Mark Shainblum": "en.wikipedia.org/wiki/Mark_Shainblum",
        "Lionel Shapiro": "en.wikipedia.org/wiki/Lionel_Shapiro",
        "Leanne Shapton": "en.wikipedia.org/wiki/Leanne_Shapton", "Sarah Sheard": "en.wikipedia.org/wiki/Sarah_Sheard",
        "Murphy O. Shewchuk": "en.wikipedia.org/wiki/Murphy_O._Shewchuk",
        "Francis Sherman": "en.wikipedia.org/wiki/Francis_Joseph_Sherman",
        "Valerie Sherrard": "en.wikipedia.org/wiki/Valerie_Sherrard",
        "Carol Shields": "en.wikipedia.org/wiki/Carol_Shields", "Erin Shields": "en.wikipedia.org/wiki/Erin_Shields",
        "Aki Shimazaki": "en.wikipedia.org/wiki/Aki_Shimazaki", "Vivek Shraya": "en.wikipedia.org/wiki/Vivek_Shraya",
        "Eric Siblin": "en.wikipedia.org/wiki/Eric_Siblin", "Maggie Siggins": "en.wikipedia.org/wiki/Maggie_Siggins",
        "Antanas Sileika": "en.wikipedia.org/wiki/Antanas_Sileika", "Ana Siljak": "en.wikipedia.org/wiki/Ana_Siljak",
        "Makeda Silvera": "en.wikipedia.org/wiki/Makeda_Silvera",
        "Louise Simard": "en.wikipedia.org/wiki/Louise_Simard_(writer)",
        "Bren Simmers": "en.wikipedia.org/wiki/Bren_Simmers",
        "Merilyn Simonds": "en.wikipedia.org/wiki/Merilyn_Simonds",
        "Colin Simpson": "en.wikipedia.org/wiki/Colin_Simpson_(electronics_professor)",
        "Andy Sinclair": "en.wikipedia.org/wiki/Andy_Sinclair",
        "Jaspreet Singh": "en.wikipedia.org/wiki/Jaspreet_Singh", "Mark Sinnett": "en.wikipedia.org/wiki/Mark_Sinnett",
        "George Sipos": "en.wikipedia.org/wiki/George_Sipos",
        "Johanna Skibsrud": "en.wikipedia.org/wiki/Johanna_Skibsrud",
        "Marsha Skrypuch": "en.wikipedia.org/wiki/Marsha_Skrypuch",
        "Josef Skvorecky": "en.wikipedia.org/wiki/Josef_Skvorecky",
        "Joshua Slocum": "en.wikipedia.org/wiki/Joshua_Slocum", "Carolyn Smart": "en.wikipedia.org/wiki/Carolyn_Smart",
        "Elizabeth Smart": "en.wikipedia.org/wiki/Elizabeth_Smart_(author)",
        "Gwen Smid": "en.wikipedia.org/wiki/Gwen_Smid", "Jean Edward Smith": "en.wikipedia.org/wiki/Jean_Edward_Smith",
        "Michael V. Smith": "en.wikipedia.org/wiki/Michael_V._Smith",
        "Neil Smith": "en.wikipedia.org/wiki/Neil_Smith_(writer)",
        "Russell Smith": "en.wikipedia.org/wiki/Russell_Smith_(writer)",
        "Carrie Snyder": "en.wikipedia.org/wiki/Carrie_Snyder",
        "Mary Soderstrom": "en.wikipedia.org/wiki/Mary_Soderstrom", "Caro Soles": "en.wikipedia.org/wiki/Caro_Soles",
        "Evan Solomon": "en.wikipedia.org/wiki/Evan_Solomon", "Madeline Sonik": "en.wikipedia.org/wiki/Madeline_Sonik",
        "J. Dewey Soper": "en.wikipedia.org/wiki/J._Dewey_Soper",
        "Carolyn Marie Souaid": "en.wikipedia.org/wiki/Carolyn_Marie_Souaid",
        "Gaétan Soucy": "en.wikipedia.org/wiki/Ga%C3%A9tan_Soucy",
        "Raymond Souster": "en.wikipedia.org/wiki/Raymond_Souster",
        "Esta Spalding": "en.wikipedia.org/wiki/Esta_Spalding",
        "Linda Spalding": "en.wikipedia.org/wiki/Linda_Spalding", "Rae Spoon": "en.wikipedia.org/wiki/Rae_Spoon",
        "Birk Sproxton": "en.wikipedia.org/wiki/Birk_Sproxton", "Eva Stachniak": "en.wikipedia.org/wiki/Eva_Stachniak",
        "Edna Staebler": "en.wikipedia.org/wiki/Edna_Staebler",
        "Harold Standish": "en.wikipedia.org/wiki/Harold_Standish",
        "Robert Stead": "en.wikipedia.org/wiki/Robert_J.C._Stead",
        "John Steffler": "en.wikipedia.org/wiki/John_Steffler",
        "Fred Stenson": "en.wikipedia.org/wiki/Fred_Stenson_(writer)",
        "Alexander Maitland Stephen": "en.wikipedia.org/wiki/Alexander_Maitland_Stephen",
        "Arran Stephens": "en.wikipedia.org/wiki/Arran_Stephens",
        "Richard Stevenson": "en.wikipedia.org/wiki/Richard_Stevenson_(poet)",
        "Shannon Stewart": "en.wikipedia.org/wiki/Shannon_Stewart_(poet)",
        "Walter Stewart": "en.wikipedia.org/wiki/Walter_Stewart_(journalist)",
        "Bill Stilwell": "en.wikipedia.org/wiki/Bill_Stilwell", "Kathy Stinson": "en.wikipedia.org/wiki/Kathy_Stinson",
        "Cassie Stocks": "en.wikipedia.org/wiki/Cassie_Stocks",
        "Aryeh Lev Stollman": "en.wikipedia.org/wiki/Aryeh_Lev_Stollman",
        "Anne Stone": "en.wikipedia.org/wiki/Anne_Stone", "Arthur G. Storey": "en.wikipedia.org/wiki/Arthur_G._Storey",
        "Allan Stratton": "en.wikipedia.org/wiki/Allan_Stratton",
        "Arthur John Arbuthnott Stringer": "en.wikipedia.org/wiki/Arthur_John_Arbuthnott_Stringer",
        "Cordelia Strube": "en.wikipedia.org/wiki/Cordelia_Strube",
        "Alan Sullivan": "en.wikipedia.org/wiki/Alan_Sullivan",
        "Gaurav Sharma": "en.wikipedia.org/wiki/Gaurav_Sharma_(author)",
        "Moez Surani": "en.wikipedia.org/wiki/Moez_Surani", "Rajiv Surendra": "en.wikipedia.org/wiki/Rajiv_Surendra",
        "Joel A. Sutherland": "en.wikipedia.org/wiki/Joel_A._Sutherland",
        "David Suzuki": "en.wikipedia.org/wiki/David_Suzuki", "Mary Swan": "en.wikipedia.org/wiki/Mary_Swan",
        "Susan Swan": "en.wikipedia.org/wiki/Susan_Swan", "Anna Swanson": "en.wikipedia.org/wiki/Anna_Swanson",
        "Robert Sward": "en.wikipedia.org/wiki/Robert_Sward",
        "Margaret Sweatman": "en.wikipedia.org/wiki/Margaret_Sweatman",
        "George Swede": "en.wikipedia.org/wiki/George_Swede",
        "Alastair Sweeny": "en.wikipedia.org/wiki/Alastair_Sweeny",
        "Guy Sylvestre": "en.wikipedia.org/wiki/Guy_Sylvestre",
        "Olivier Sylvestre": "en.wikipedia.org/wiki/Olivier_Sylvestre",
        "Harry L. Symons": "en.wikipedia.org/wiki/Harry_L._Symons",
        "Scott Symons": "en.wikipedia.org/wiki/Scott_Symons", "Shawn Syms": "en.wikipedia.org/wiki/Shawn_Syms",
        "Anne Szumigalski": "en.wikipedia.org/wiki/Anne_Szumigalski",
        "Tanya Talaga": "en.wikipedia.org/wiki/Tanya_Talaga", "Kenneth Tam": "en.wikipedia.org/wiki/Kenneth_Tam",
        "Mariko Tamaki": "en.wikipedia.org/wiki/Mariko_Tamaki",
        "Shelley Tanaka": "en.wikipedia.org/wiki/Shelley_Tanaka",
        "Jordan Tannahill": "en.wikipedia.org/wiki/Jordan_Tannahill",
        "Jules-Paul Tardivel": "en.wikipedia.org/wiki/Jules-Paul_Tardivel",
        "Gladys Taylor": "en.wikipedia.org/wiki/Gladys_Taylor_(publisher)",
        "Timothy Taylor": "en.wikipedia.org/wiki/Timothy_Taylor_(writer)",
        "Ningeokuluk Teevee": "en.wikipedia.org/wiki/Ningeokuluk_Teevee",
        "Wayne Tefs": "en.wikipedia.org/wiki/Wayne_Tefs", "Richard Teleky": "en.wikipedia.org/wiki/Richard_Teleky",
        "Charles Templeton": "en.wikipedia.org/wiki/Charles_Templeton",
        "John Terpstra": "en.wikipedia.org/wiki/John_Terpstra",
        "Bill Terry": "en.wikipedia.org/wiki/Bill_Terry_(author)",
        "Souvankham Thammavongsa": "en.wikipedia.org/wiki/Souvankham_Thammavongsa",
        "Yasuko Thanh": "en.wikipedia.org/wiki/Yasuko_Thanh",
        "France Théoret": "en.wikipedia.org/wiki/France_Th%C3%A9oret",
        "Denis Thériault": "en.wikipedia.org/wiki/Denis_Th%C3%A9riault",
        "Yves Thériault": "en.wikipedia.org/wiki/Yves_Th%C3%A9riault",
        "Sharon Thesen": "en.wikipedia.org/wiki/Sharon_Thesen",
        "Serge Patrice Thibodeau": "en.wikipedia.org/wiki/Serge_Patrice_Thibodeau",
        "Madeleine Thien": "en.wikipedia.org/wiki/Madeleine_Thien",
        "Kai Cheng Thom": "en.wikipedia.org/wiki/Kai_Cheng_Thom",
        "Audrey Thomas": "en.wikipedia.org/wiki/Audrey_Thomas", "Colin Thomas": "en.wikipedia.org/wiki/Colin_Thomas",
        "Joan Thomas": "en.wikipedia.org/wiki/Joan_Thomas",
        "John Thompson": "en.wikipedia.org/wiki/John_Thompson_(poet)",
        "Peggy Thompson": "en.wikipedia.org/wiki/Peggy_Thompson_(screenwriter)",
        "Jan Thornhill": "en.wikipedia.org/wiki/Jan_Thornhill",
        "Elizabeth Thornton": "en.wikipedia.org/wiki/Elizabeth_Thornton",
        "Russell Thornton": "en.wikipedia.org/wiki/Russell_Thornton_(writer)",
        "Kim Thúy": "en.wikipedia.org/wiki/Kim_Th%C3%BAy", "Sara Tilley": "en.wikipedia.org/wiki/Sara_Tilley",
        "Miriam Toews": "en.wikipedia.org/wiki/Miriam_Toews", "Morley Torgov": "en.wikipedia.org/wiki/Morley_Torgov",
        "Lola Lemire Tostevin": "en.wikipedia.org/wiki/Lola_Lemire_Tostevin",
        "Gérald Tougas": "en.wikipedia.org/wiki/G%C3%A9rald_Tougas", "Paul Toupin": "en.wikipedia.org/wiki/Paul_Toupin",
        "Matthew J. Trafford": "en.wikipedia.org/wiki/Matthew_J._Trafford",
        "Michaël Trahan": "en.wikipedia.org/wiki/Micha%C3%ABl_Trahan",
        "Catharine Parr Traill": "en.wikipedia.org/wiki/Catharine_Parr_Traill",
        "Rhea Tregebov": "en.wikipedia.org/wiki/Rhea_Tregebov", "Lise Tremblay": "en.wikipedia.org/wiki/Lise_Tremblay",
        "Michel Tremblay": "en.wikipedia.org/wiki/Michel_Tremblay",
        "Sylvain Trudel": "en.wikipedia.org/wiki/Sylvain_Trudel",
        "Stuart Trueman": "en.wikipedia.org/wiki/Stuart_Trueman",
        "Karen X. Tulchinsky": "en.wikipedia.org/wiki/Karen_X._Tulchinsky",
        "Élise Turcotte": "en.wikipedia.org/wiki/%C3%89lise_Turcotte",
        "Pierre Turgeon": "en.wikipedia.org/wiki/Pierre_Turgeon_(writer)",
        "Chris Turner": "en.wikipedia.org/wiki/Chris_Turner_(author)",
        "Michael Turner": "en.wikipedia.org/wiki/Michael_Turner_(musician)",
        "Marie Uguay": "en.wikipedia.org/wiki/Marie_Uguay", "Priscila Uppal": "en.wikipedia.org/wiki/Priscila_Uppal",
        "Jane Urquhart": "en.wikipedia.org/wiki/Jane_Urquhart",
        "Geoffrey Ursell": "en.wikipedia.org/wiki/Geoffrey_Ursell",
        "David UU (David W. Harris)": "en.wikipedia.org/wiki/David_UU_(David_W._Harris)",
        "W. D. Valgardson": "en.wikipedia.org/wiki/W._D._Valgardson",
        "Pierre Vallières": "en.wikipedia.org/wiki/Pierre_Valli%C3%A8res",
        "Edo Van Belkom": "en.wikipedia.org/wiki/Edo_Van_Belkom",
        "Richard Van Camp": "en.wikipedia.org/wiki/Richard_Van_Camp",
        "Guy Vanderhaeghe": "en.wikipedia.org/wiki/Guy_Vanderhaeghe",
        "Aritha Van Herk": "en.wikipedia.org/wiki/Aritha_Van_Herk",
        "A. E. van Vogt": "en.wikipedia.org/wiki/A._E._van_Vogt", "Jean Vanier": "en.wikipedia.org/wiki/Jean_Vanier",
        "M. G. Vassanji": "en.wikipedia.org/wiki/M._G._Vassanji",
        "R. M. Vaughan": "en.wikipedia.org/wiki/R._M._Vaughan",
        "Guillermo Verdecchia": "en.wikipedia.org/wiki/Guillermo_Verdecchia",
        "Robert Verdun": "en.wikipedia.org/wiki/Robert_Verdun",
        "Paul Vermeersch": "en.wikipedia.org/wiki/Paul_Vermeersch",
        "Katherena Vermette": "en.wikipedia.org/wiki/Katherena_Vermette",
        "Gilles Vigneault": "en.wikipedia.org/wiki/Gilles_Vigneault",
        "Margaret Visser": "en.wikipedia.org/wiki/Margaret_Visser",
        "Élisabeth Vonarburg": "en.wikipedia.org/wiki/%C3%89lisabeth_Vonarburg",
        "Garth Von Buchholz": "en.wikipedia.org/wiki/Garth_Von_Buchholz",
        "John Voss": "en.wikipedia.org/wiki/John_Voss_(sailor)", "Caroline Vu": "en.wikipedia.org/wiki/Caroline_Vu",
        "Prvoslav Vujcic": "en.wikipedia.org/wiki/Prvoslav_Vujcic", "Dan Vyleta": "en.wikipedia.org/wiki/Dan_Vyleta",
        "Marie Wadden": "en.wikipedia.org/wiki/Marie_Wadden",
        "Richard Wagamese": "en.wikipedia.org/wiki/Richard_Wagamese",
        "Colleen Wagner": "en.wikipedia.org/wiki/Colleen_Wagner", "Fred Wah": "en.wikipedia.org/wiki/Fred_Wah",
        "David Walker": "en.wikipedia.org/wiki/David_Walker_(author)",
        "Joan Walker": "en.wikipedia.org/wiki/Joan_Walker", "Bronwen Wallace": "en.wikipedia.org/wiki/Bronwen_Wallace",
        "Frederick William Wallace": "en.wikipedia.org/wiki/Frederick_William_Wallace",
        "William Stewart Wallace": "en.wikipedia.org/wiki/William_Stewart_Wallace",
        "Paul A. W. Wallace": "en.wikipedia.org/wiki/Paul_A._W._Wallace",
        "Tom Walmsley": "en.wikipedia.org/wiki/Tom_Walmsley", "Eric Walters": "en.wikipedia.org/wiki/Eric_Walters",
        "John Leigh Walters": "en.wikipedia.org/wiki/John_Leigh_Walters",
        "Russell Wangersky": "en.wikipedia.org/wiki/Russell_Wangersky",
        "Ryan Ward": "en.wikipedia.org/wiki/Ryan_Ward_(actor)",
        "Sabrina Ward Harrison": "en.wikipedia.org/wiki/Sabrina_Ward_Harrison",
        "Dianne Warren": "en.wikipedia.org/wiki/Dianne_Warren",
        "David Watmough": "en.wikipedia.org/wiki/David_Watmough",
        "Sheila Watson": "en.wikipedia.org/wiki/Sheila_Watson_(writer)",
        "Alison Watt": "en.wikipedia.org/wiki/Alison_Watt_(writer)",
        "Thomas Waugh": "en.wikipedia.org/wiki/Thomas_Waugh", "Alison Wearing": "en.wikipedia.org/wiki/Alison_Wearing",
        "Jessica L. Webb": "en.wikipedia.org/wiki/Jessica_L._Webb",
        "Barry Webster": "en.wikipedia.org/wiki/Barry_Webster_(writer)",
        "John Weier": "en.wikipedia.org/wiki/John_Weier", "Steve Weiner": "en.wikipedia.org/wiki/Steve_Weiner",
        "William Weintraub": "en.wikipedia.org/wiki/William_Weintraub",
        "Helen Weinzweig": "en.wikipedia.org/wiki/Helen_Weinzweig",
        "Merrily Weisbord": "en.wikipedia.org/wiki/Merrily_Weisbord",
        "Elizabeth Wellburn": "en.wikipedia.org/wiki/Elizabeth_Wellburn",
        "Zachariah Wells": "en.wikipedia.org/wiki/Zachariah_Wells",
        "Andrew Westoll": "en.wikipedia.org/wiki/Andrew_Westoll",
        "Robert Paul Weston": "en.wikipedia.org/wiki/Robert_Paul_Weston",
        "Michael Wex": "en.wikipedia.org/wiki/Michael_Wex", "Ron Weyman": "en.wikipedia.org/wiki/Ron_Weyman",
        "Dawud Wharnsby": "en.wikipedia.org/wiki/Dawud_Wharnsby",
        "Thomas Wharton": "en.wikipedia.org/wiki/Thomas_Wharton_(author)",
        "Sherry White": "en.wikipedia.org/wiki/Sherry_White",
        "Joshua Whitehead": "en.wikipedia.org/wiki/Joshua_Whitehead",
        "William Whitehead": "en.wikipedia.org/wiki/William_Whitehead_(Canadian_writer)",
        "Zoe Whittall": "en.wikipedia.org/wiki/Zoe_Whittall", "Rudy Wiebe": "en.wikipedia.org/wiki/Rudy_Wiebe",
        "Helen Waldstein Wilkes": "en.wikipedia.org/wiki/Helen_Waldstein_Wilkes",
        "Fred Williams": "en.wikipedia.org/wiki/Fred_Williams_(journalist)",
        "Jeffery Williams": "en.wikipedia.org/wiki/Jeffery_Williams",
        "Deborah Willis": "en.wikipedia.org/wiki/Deborah_Willis_(author)",
        "Alan R. Wilson": "en.wikipedia.org/wiki/Alan_R._Wilson",
        "Douglas Wilson": "en.wikipedia.org/wiki/Douglas_Wilson_(activist)",
        "Eric Wilson": "en.wikipedia.org/wiki/Eric_Wilson_(author)",
        "Ethel Wilson": "en.wikipedia.org/wiki/Ethel_Wilson",
        "John Wilson": "en.wikipedia.org/wiki/John_Wilson_(Canadian_young_adults%27_writer)",
        "Jonathan Wilson": "en.wikipedia.org/wiki/Jonathan_Wilson_(actor)",
        "Robert Charles Wilson": "en.wikipedia.org/wiki/Robert_Charles_Wilson",
        "Sheri-D Wilson": "en.wikipedia.org/wiki/Sheri-D_Wilson",
        "Jia Qing Wilson-Yang": "en.wikipedia.org/wiki/Jia_Qing_Wilson-Yang",
        "Carol Windley": "en.wikipedia.org/wiki/Carol_Windley", "Rob Winger": "en.wikipedia.org/wiki/Rob_Winger",
        "Kathleen Winter": "en.wikipedia.org/wiki/Kathleen_Winter",
        "Michael Winter": "en.wikipedia.org/wiki/Michael_Winter_(writer)",
        "Kari-Lynn Winters": "en.wikipedia.org/wiki/Kari-Lynn_Winters",
        "Wyndham Wise": "en.wikipedia.org/wiki/Wyndham_Wise", "Adele Wiseman": "en.wikipedia.org/wiki/Adele_Wiseman",
        "Alan Woo": "en.wikipedia.org/wiki/Alan_Woo", "Jaime Woo": "en.wikipedia.org/wiki/Jaime_Woo",
        "George Woodcock": "en.wikipedia.org/wiki/George_Woodcock",
        "Susan Wood": "en.wikipedia.org/wiki/Susan_Wood_(science_fiction)",
        "Marnie Woodrow": "en.wikipedia.org/wiki/Marnie_Woodrow",
        "Lance Woolaver": "en.wikipedia.org/wiki/Lance_Woolaver",
        "Eric Wright": "en.wikipedia.org/wiki/Eric_Wright_(writer)",
        "J. F. C. Wright": "en.wikipedia.org/wiki/J._F._C._Wright",
        "L. R. Wright": "en.wikipedia.org/wiki/L._R._Wright",
        "Richard B. Wright": "en.wikipedia.org/wiki/Richard_B._Wright",
        "Tim Wynne-Jones": "en.wikipedia.org/wiki/Tim_Wynne-Jones", "Tim Wynveen": "en.wikipedia.org/wiki/Tim_Wynveen",
        "Xiaowen Zeng": "en.wikipedia.org/wiki/Xiaowen_Zeng", "Joel Yanofsky": "en.wikipedia.org/wiki/Joel_Yanofsky",
        "Pierre Yergeau": "en.wikipedia.org/wiki/Pierre_Yergeau", "Ying Chen": "en.wikipedia.org/wiki/Ying_Chen",
        "Jean Yoon": "en.wikipedia.org/wiki/Jean_Yoon", "Alissa York": "en.wikipedia.org/wiki/Alissa_York",
        "Elwy Yost": "en.wikipedia.org/wiki/Elwy_Yost", "Graham Yost": "en.wikipedia.org/wiki/Graham_Yost",
        "David Young": "en.wikipedia.org/wiki/David_Young_(Canadian_playwright)",
        "d'bi young": "en.wikipedia.org/wiki/D%27bi_young", "Ian Young": "en.wikipedia.org/wiki/Ian_Young_(writer)",
        "Scott Young": "en.wikipedia.org/wiki/Scott_Young_(writer)",
        "Josée Yvon": "en.wikipedia.org/wiki/Jos%C3%A9e_Yvon", "Eve Zaremba": "en.wikipedia.org/wiki/Eve_Zaremba",
        "Robert Zend": "en.wikipedia.org/wiki/Robert_Zend", "David Zieroth": "en.wikipedia.org/wiki/David_Zieroth",
        "Larry Zolf": "en.wikipedia.org/wiki/Larry_Zolf", "Rachel Zolf": "en.wikipedia.org/wiki/Rachel_Zolf",
        "Daniel Zomparelli": "en.wikipedia.org/wiki/Daniel_Zomparelli",
        "Carolyn Zonailo": "en.wikipedia.org/wiki/Carolyn_Zonailo", "Jan Zwicky": "en.wikipedia.org/wiki/Jan_Zwicky"}

for name in data:
    split_names = name.split()
    first_name = split_names[0]
    last_name = split_names[-1]
    print(first_name[0].upper() + first_name[1:].lower() + last_name[0].upper() + last_name[1:].lower())
